### ISSUE TITLE
RTL mode Angular1 Material Tabs not working.

### ISSUE THREAD

**Issue by anilk533** [angular/material#11025]
**RTL direction for material tabs not working.**
here is the issue.
https://codepen.io/djidel/pen/NpMpmY

please let me know how to solve

thank you

#9487  #3538  #material #mdTabs #1078  #10156 #rtl

**Comment by Splaktar** [comment]
Fixed in https://github.com/angular/material/commit/338ca278f40c5de8c0ac1173946492b45a41a22a which is part of 1.1.5. I see that your CodePen is for AngularJS Material 1.1.3. Please submit issues and reproductions only using the latest version of the library.

**Comment by Oneril** [comment]
This issue is still reproducible in the last version!!
https://codepen.io/anon/pen/BVBwjw
