### ISSUE TITLE
md-list-item: ng-href or ng-click makes ChromeVox Next repeatedly announce the element

### ISSUE THREAD

**Issue by michaelcupino** [angular/material#11120]
### Bug, feature request, or proposal:

Using md-list-item with ng-href or ng-click makes ChromeVox Next repeatedly announce the element 3 times

### What is the expected behavior?

Using md-list-item with ng-href or ng-click should make ChromeVox Next announce the element once

### What is the current behavior?

Using md-list-item with ng-href or ng-click makes ChromeVox Next repeatedly announce the element 3 times

##### [CodePen Demo](http://codepen.io/team/AngularMaterial/pen/bEGJdd) which shows your issue: 

https://codepen.io/michaelcupino/pen/LQjOVX

Forked from: https://material.angularjs.org/latest/demo/list

##### Detailed Reproduction Steps: 

`<md-list-item ng-click="null">...</md-list-item>`
or
`<md-list-item ng-href="https://www.google.com">...</md-list-item>`

### What is the use-case or motivation for changing an existing behavior?

Providing a delightful experience to ChromeVox Next users that use my team's app.

### Which versions of AngularJS, Material, OS, and browsers are affected?

1.6.7/angular.js
v1.1.7/angular-material.js
Chrome OS Version 63.0.3239.140

### Is there anything else we should know? Stack Traces, Screenshots, etc.

Screencast demonstrating the issue:
https://drive.google.com/file/d/1mSZoDJlNrfmKOonqh19AIJ3aOZzUqJ88/view?usp=sharing

[2018-02-13-screencast-of-md-list-item-chromevox.zip](https://github.com/angular/material/files/1722338/2018-02-13-screencast-of-md-list-item-chromevox.zip)

In the screencast, ChromeVox Next announces (verbatim): Min Li Chen. Brunch this weekend? I'll be in your neighborhood doing errands. Button; Min Li Chen. Brunch this weekend? I'll be in your neighborhood doing errands; Min Li Chen. Brunch this weekend? I'll be in your neighborhood doing errands. List item;

**Comment by codymikol** [comment]
It seems like this is something that has been fixed in the latest version of ChromeVox, I just tested this and the screen reader only reads the content of the button once on both focus and click.

**Comment by Splaktar** [comment]
@codymikol thank you very much for testing that and letting me know!

@michaelcupino I'm going to close this, but please let me know if latest version of ChromeVox doesn't fix this for you.
