### ISSUE TITLE
buttons don't respond to touch events within bottom sheet

### ISSUE THREAD

**Issue by Johnnyrook777** [angular/material#1179]
touching md-buttons contained within a md-bottom-sheet do not respond.
This can be seen on the demos page when using an ipad or google chrome emulating touch

**Comment by MilosStanic** [comment]
I am experiencing same problem with touch. I get error: 
Uncaught TypeError: Cannot read property '0' of undefined
twice for each touch on any element in bottom sheet. 
The error is reported in the getY() function.

**Comment by ajoslin** [comment]
This is fixed now.

**Comment by Johnnyrook777** [comment]
Thanks Andrew, good work

**Comment by MilosStanic** [comment]
I just updated angular-material to 0.7.0 and I still can't make touch events work in $mdBottomSheet. 
Plus, angular-material still requires hammer.js, which I understood was phased out. 

The only way to make touch events work for me is to modify angular-material.js function getY like this: 
```
/**
 * Helper function to find the Y aspect of various touch events.
**/
function getY(e) {
  if(e.originalEvent){
    e = e.originalEvent;
  }          
  var touch = e.touches && e.touches.length ? e.touches[0] : e.changedTouches[0];
  return touch.clientY;
}
```
(this is not my solution, I think I picked it up from some other issue here)

**Comment by infomofo** [comment]
@MilosStanic I had a similar problem to what you're experiencing. When I upgraded to the 0.8.0-rc1 bower distribution it began to work as expected.
