### ISSUE TITLE
in-consequent use of mdInputContainer (look at the mdCheckbox) 

### ISSUE THREAD

**Issue by SanderElias** [angular/material#1268]
I created [this sample on plunker](http://plnkr.co/edit/M22sy0AI7Bax3Cop3OmI?p=preview) to demonstrate a few issues I'm having with forms. 

```
            <md-input-container>
               <label>Show form JSON?</label>
               <md-checkbox ng-model="showForm" aria-label="showForm"></md-checkbox>
            </md-input-container>
```

This does not work. I know how to fix it, but that's not the point. When building a form, all inputs should be formatted in a uniform way, to lessen programmer discomfort ;)

I liked the idea Thomas put out in the list-group to make it like this:
```
   <md-input-container label="xxxx">
      <md-combobox>
   </md-input-container>
```

This is not an exact copy of his idea, he was just making it so for inputs, but it should work the same way for all forms of inputs, so check-boxes/radios/switches/whatever should follow the same flow.

**Comment by marcysutton** [comment]
I think a goal should also be to discourage poor markup practices. `mdInputContainer` does some crafty things under the hood to bind the `<label>` to `<input>`. It adds a `for` attribute to the label and a unique `id` to the input. Which is cool, except it also means we're saying it's okay to not properly bind these two elements, which is a huge problem for accessibility of web forms.

I have also seen no label at all in the wild already, which is why [this issue](https://github.com/angular/material/issues/1242) was opened:
```
<md-input-container>
    <md-checkbox ng-model="showForm"></md-checkbox>
</md-input-container>
```

By encouraging `label="xxxx"`, we are being more explicit that labeling magic is happening inside the component. We can still allow `<label>` to be included by the developer. But it should log a warning to the console if there is no proper label, in either style.

**Comment by SanderElias** [comment]
@marcysutton I agree with this. An warning should be thrown if no label is attached.
I think the automated For<->id binding is not promoting bad coding habits. I always found those things a real nuisance, and in direct conflict with DRY.
Let me show you a sample:

```
<md-input-container>
     <label for="myInputThingieWhereIOnlyNeedThisIdForThisLabel">Relevant label</label>
    <input type="text" ng-model="showForm" id="myInputthingieWhereIOnlyNeedThisIdForThisLabel">
</md-input-container>
```
versus
```
<md-input-container label='Relevant Label'>
    <input type="text" ng-model="showForm" >
</md-input-container>
```
I think the second one is much clearer. and a lot less typing, and less change on error. Don't believe me? my first sample will not show an label! I made an typo in the ID

Also, if you need to nest templates and forms, the change on ID's (that only exists for the labels) collide becomes an real problem. This is avoided by not using them hand!

**Comment by ajoslin** [comment]
I don't like the `label` attribute. 

It promotes two API surfaces again: both a label attribute and a label element.

`label="some label"`: 19 chars
`<label>some label</label>`: 26 chars

There is little difference, and one promotes API consistency.

At the end of the day, a `label` attribute is never going to be powerful enough.  You can't put ng-if, ng-hide, or some crazy HTML inside of a label attribute. I'm in favor of the most power API only.

**Comment by SanderElias** [comment]
@ajoslin I don't mind the extra typing. As long as the api/interface is uniform, I can live with it. However, I prefer to stay clear from the manual binding as I explained above.

Just as a reminder, this was not an issue about a label attribute VS an label tag, The issue was about an uniform way to implement all input elements and labels (input/ mdCheckbutton mdSwwitch/ whatever)

**Comment by gkalpak** [comment]
I still can't imagine how a floating label would work for components such as checkboxes, switches etc. 
If we're not looking for a floating label, then I don't see why `<md-checkbox/switch>` would be placed inside of an `<md-input-container>`. Making `ngMessages` look nice with these components would make sense though.

**Comment by SanderElias** [comment]
@gkalpak This is not about the floating label. This is on how to create an API that is as uniform as possible. Meaning, wherever you need a label, it should be working the same regardless the input type

**Comment by gkalpak** [comment]
Maybe it's me, but I still don't get it.
Are you saying `mdInputContainer` should be handling the "laying out" and styling of a label for various control elements (e.g. `input`, `mdSwitch`, `mdCheckbox` etc), possibly styling it differently per control element ?

**Comment by marcysutton** [comment]
We're saying there should be a consistent API for labeling form controls in Angular Material. By providing explicit ways to label components, it reduces the possibility for ineffective labels. Here are some examples:

We should definitely support the `<label>` element (Material dynamically adds `for` and `id`, which helps):
```
<md-input-container>
    <label for="componentXXX">First Name</name>
    <input type="text" ng-model="" id="componentXXX">
</md-input-container>
```

But `<label>` is likely to be forgotten altogether, and is not used with all components (i.e. checkbox/switch).

A `label=""` attribute on the wrapper is clearly going to be manipulated into something else, as there is no `label` attribute already in HTML5:
```
<md-input-container label="First name">
    <input type="text" ng-model="">
</md-input-container>
```
Including `label=""` would tell Material to add `aria-label=""` to the input (it has to go on the INPUT, not the wrapper, to be effective). This would be easy to mess up and is why I'm pushing for consistent use of `label` on the wrapper. It would give developers two ways to label a component and have it work with assistive technologies.

**Comment by SanderElias** [comment]
@gkalpak In addition to what @marcysutton is saying. An generic approach to labeling controls has aside from the benefits for accessibility, a better an more uniform template api, lessening the cognitive burden, and with that decreasing the change of programmer/typing errors.
Ideally I would wish for the following template to work as one would expect:
```
<md-input-container>
  <label>First name</label>
  <input type="text" ng-model='model.firstname'>
</md-input-container>
<md-input-container>
  <label>I agree with the point</label>
  <md-checkbox ng-model='model.AgreeToPoint'></md-checkbox>
</md-input-container>
<md-input-container>
  <label>I like to flip switches</label>
  <md-switch ng-model="model.likeSwitches"></md-switch>
</md-input-container>
<md-input-container>
  <label>MD hotness</label>
  <md-slider ng-model="model.hotness"></md-slider>
</md-input-container>
<md-radio-group ng-model="model.likeAngular">
  <md-input-container>
     <label>Nah</label>
     <md-radio-button ng-value="0"></md-radio-button>
  </md-input-container>
  <md-input-container>
     <label>a Bit</label>
     <md-radio-button ng-value="1"></md-radio-button>
  </md-input-container>
  <md-input-container>
     <label>Woah, can't live without anymore</label>
     <md-radio-button ng-value="2"></md-radio-button>
  </md-input-container>
</md-radio-group>
```

See what I mean?

**Comment by gkalpak** [comment]
> See what I mean ?

@SanderElias: Ehm...not really :confused: 

--
> I would wish for the following template to work as one would expect

I am not at all sure what to expect :confused:

--
I see `mdSwitch/Checkbox/RadioButton` as different components. They might "emulate" `<input>` elements (or rather their functionality), but there are no `input`s actually, so I am not sure what you expect `<md-input-container>` to do with them (or why you would expect `md-input-container` to be able to handle them in some way).
If nothing else, this seems too verbose too me (having 2 extra lines for each component, not to mention one extra DOM element).

Why not accept that `input` should be wrapped in `md-input-containers`, whereas `mdSwitch/Checkbox/RadioButton` (which are not `input`s) shouldn't.

--
Anyway, it's just my point of view. Since there seem to be a few people thinking this is a good idea, it probably is :) Thx for taking the time to clarify (even if I don't get it :smile:)

**Comment by SanderElias** [comment]
@gkalpak, does it help if when you know that all those mdXXX translate to their native `<input type="radio/checkbox/date/range/...">`? 
All in all, every one of those elements allows user *input*, so they should have an label and an aria-label.

**Comment by lumalav** [comment]
This should be reopened. @SanderElias had a point. **md-checkbox** is another _input_ and should behave the same as others when used inside an **md-input-container**
