### ISSUE TITLE
mdInputContainer: cannot submit form using enter key

### ISSUE THREAD

**Issue by yarl** [angular/material#1291]
Please take a look at [this fiddle](http://jsfiddle.net/o8hhbhp7/1/), right now you cannot submit `<form>` when click Enter key on password field.

For addition, version `v0.7.0-rc3-master-1c97333` works fine.

**Comment by jonnyarnold** [comment]
The issue is bigger than that...

Currently *any* `<form>` with more than one `<input>` cannot be submitted using the enter key. Here is an example of the Enter key successfully submitting a form:

http://jsfiddle.net/o8hhbhp7/6/

And here is the same example, only with the addition of a Submit button, which does not have the Enter functionality:

http://jsfiddle.net/o8hhbhp7/7/

**Comment by PaulMougel** [comment]
Confirming on Chrome, Safari & Firefox.

**Comment by yarl** [comment]
IE10 console for `v0.7.0-master-e4397de`:

    SCRIPT445: Object doesn't support this action 
    angular-material.js, line 1231 character 7

Actually you cannot use form at all  now on IE10.

**Comment by ajoslin** [comment]
Fixed via e190abefb82ece4a8b5d2335634d9538eaa86388

**Comment by jonnyarnold** [comment]
Can we reopen this? There is still an issue when there is more than one `<input>`; see this Fiddle:

http://jsfiddle.net/o8hhbhp7/8/

I expect to be able to press enter on either field and it should submit.

**Comment by ajoslin** [comment]
You have to have a submit button for the form to submit: http://jsfiddle.net/hh5xh7gf/

**Comment by gkalpak** [comment]
You don't always need a submit button.
Angular has an explanation of what's going on with form submission:https://docs.angularjs.org/api/ng/directive/form

**Comment by jonnyarnold** [comment]
Well that sorts my issue out - good to know, and thanks!

**Comment by dreamsoftech** [comment]
:+1:
