### ISSUE TITLE
mdSelect: options are duplicated if the model value is pre-set

### ISSUE THREAD

**Issue by yboycn** [angular/material#1676]
http://codepen.io/anon/pen/YPvzBE

The select has 3 options, apple, orange and mango. However, when I set 'selected' to 'apple', the options I got in the drop down is:
apple
apple
apple
orange
orange
orange
mango
mango
mango

**Comment by ngraef** [comment]
This was fixed in 9e0ca4430f9f3add077a21ccb5a963e48a7f7d83.

**Comment by rschmukler** [comment]
Indeed, it was fixed. Closing.

**Comment by leeyeh** [comment]
Thanks for the fix. However, it still shows the placeholder text when the model value is preset.

see: http://codepen.io/anon/pen/OPEjmd

I can file a new issue if preferable.

**Comment by leeyeh** [comment]
Duplicate of #1699. Sorry.
