### ISSUE TITLE
mdSelect does not display list of items or allow you to select its items from an ngModal or mdDialog

### ISSUE THREAD

**Issue by adonix** [angular/material#1701]
Not sure if this bug was ever documented but just tried it with version 0.8.1 and it is still happening. 

Steps to reproduce:

Place md-select inside a ngModal or md-dialog
Open modal or dialog
Open select (observer that no list is ever displayed)
Click somewhere outside the modal/dialog to have it removed
Observe select is still open in the middle of the screen

**Comment by maksimlikharev** [comment]
same for me, except dropdown opens in the top right corner and stays open after the dialog is closed

**Comment by kschwidder** [comment]
With the current master it is fixed ! I have run into the same issues with md-dialog, md-bottomsheet etc.

**Comment by rschmukler** [comment]
Yeah, it's fixed.

**Comment by adonix** [comment]
@rschmukler I just installed from master and problem is still there with ngModals.  Am is missing something here?

**Comment by adonix** [comment]
Basically the issue that I still see occurring with #master or 0.8.2 is that the selection list displayed by mdSelect goes to the back of the modal. Once you close the modal, you can briefly see it and then it disappears as the modal is closing.

**Comment by adonix** [comment]
Hi,

Here's a demo (http://plnkr.co/edit/1s9d8NIXyrxZhmsLoWtn) of the issue that is still happening. I would love for this get fixed since it is very common for mdSelects to be used within modals

**Comment by henlz** [comment]
I running into the same problem when I click outside the dialog and the options stay at the screen blocking everything else with a backdrop. Currently using the 0.8.0 version, I'm waiting for Webjars to provide the new version (0.8.3). 

Is it really fixed?

**Comment by rschmukler** [comment]
It doesn't look like it's fixed, so the issue is open

**Comment by kschwidder** [comment]
As a workaround I have disabled the backdrop feature. Since my dialogs are somehow complex it makes sense. I would prefer using backdrop if I only show information without interaction.

**Comment by srdone** [comment]
@adonix - I took a look at your plunker and I noticed that you were using a mix of Angular UI Bootstrap and Angular Material. I've saved an updated plunker (http://plnkr.co/edit/3PZUfF) that shows the proper way to do this using the $mdDialog service. It seems to work just fine now.

**Comment by marcysutton** [comment]
Can you verify whether this is still an issue using the code currently on master?

**Comment by adonix** [comment]
@srdone Thanks for looking into this. So is it the norm that we can't (or shouldn't) mix Angular UI Bootstrap components with Angular Material?

@marcysutton I can verity (using @srdone 's plunker) that the issue does not occur using mdDialog, but it still happens with ngModal.

**Comment by srdone** [comment]
@adonix, I don't know what the official stance on using the two together, but it has been my experience that using what is already provided (where possible) results in the fewest errors. $mdDialog is excellent, so I don't see a need to mix the two, but you may have use cases I don't know about.

**Comment by rschmukler** [comment]
The issue is that `ui-bootstrap` sets a very high z-index on the modal so it's going above our menu. You could probably manually fiddle around with the z-index and CSS selectors to make it work, but in general we don't support mixing the frameworks. Closing.
