### ISSUE TITLE
md-select not working with ng-disabled

### ISSUE THREAD

**Issue by nil4you** [angular/material#1705]
if ng-disabled is false still md-select is not opening

**Comment by bOOm-X** [comment]
+1
I have the same issue (v0.8.1).
Nothing show up when clicking to expand the select when it have a ng-disabled attribute

**Comment by Novashock** [comment]
I am having the same issue. I am displaying the option Dynamically, and I am able to see the list of Item in my view, but not in a section modal format.

**Comment by ngraef** [comment]
Duplicate of #1674.

**Comment by b-crone** [comment]
Have you tried using ng-attr-disabled? I have used this attribute with a secondary md-select that is dynamically populated. This could be a workaround until ng-disabled is supported.

Here is a sample:
ng-attr-disabled="{{ foo == '' ? 'disabled' : undefined }}"

**Comment by rschmukler** [comment]
Duplicate of #1674, and subsequently #1646.

**Comment by nil4you** [comment]
@rschmukler is issue solved now? need to take latest version of build ?

**Comment by bOOm-X** [comment]
I tested the 0.8.2 version and the issue is still present. I did not test at @head

**Comment by bOOm-X** [comment]
tested in 0.8.3 and it s working now !

Thanks !

**Comment by nil4you** [comment]
thanks for your info @bOOm-X

**Comment by tylerfloyd** [comment]
I tested in 0.8.3 and the bug is still present.

**Comment by ngraef** [comment]
@tylerfloyd Do you have a code sample? This was fixed in 60514054984c3d1c5577c5150e80e7ca9e3a4083 and [works for me](http://codepen.io/anon/pen/ZYMVPG?editors=101).

**Comment by tylerfloyd** [comment]
Not at the moment but, I am updating a scope variable to be true or false from a directive.

**Comment by tylerfloyd** [comment]
@ngraef Created a new test page and cannot replicate. Must be something else in the code.  Thanks!

**Comment by nil4you** [comment]
@ngraef I can not say as I have not checked it yet.

**Comment by RossHerrera** [comment]
Tested in v1.0.7 and still not working.

**Comment by DevVersion** [comment]
@RossHerrera Please file a new issue.

**Comment by patrikx3** [comment]
md-select not working with disabled with fieldset.

**Comment by Luiggi370z** [comment]
I think they forgot to include the styles for **md-select** with a disabled parent, here is:

`[disabled] md-input-container > md-select {
    pointer-events: none;
}

[disabled] md-input-container > md-select .md-select-value {
    background-position: bottom -1px left 0;
    background-size: 4px 1px;
    background-repeat: repeat-x;
    border-bottom-color: transparent;
    color: rgba(0,0,0,0.38);
    background-image: linear-gradient(90deg,rgba(0,0,0,0.38) 0,rgba(0,0,0,0.38) 33%,transparent 0);
}`

It works for me :)
