### ISSUE TITLE
ie11: Terrible performance, but not with LumX

### ISSUE THREAD

**Issue by ross-nordstrom** [angular/material#1771]
## Overview
We have an application we're trying to release to production using Angular Material, but cannot get it to perform in IE10/11. After a lot of struggling (is Angular the problem? Is this, that, or the other dependecy a problem?), we've found that Angular Material framework is simply slow in IE. In comparison, [LumX](http://ui.lumapps.com/) (a different Material Design + Angular framework) works fine in IE10/11.

## Plnkr Demo of the Problem
To demonstrate the problem, I implemented a simple page with a Toolbar and list of Items in both Angular Material and LumX. They both perform equally well in Chrome, but ng-material is **much** slower in IE.

### Performance Comparison
To test performance, I did the following:
 * Entered `900` in input box and submit (click `Add People` or hit Enter key)
 * Visually stop-watch the time from submission to the `(xxxx)` number updating

Plnkr | Chrome | IE11
---|---:|---:
[ng-material demo](http://embed.plnkr.co/HtOJPtzfZFlvWAlCt58n/preview) | ~1s | ~8s
[lumx demo](http://embed.plnkr.co/MGDRYEtyQWmULckRVh8y/preview) | <1s | ~1s

### Versions Used
Laptop: `Win7 64-bit, 16gb RAM, Core i7`
Chrome version: `Version 40.0.2214.115 m`
IE11 version: `11.0.9600.17633`

While I'd prefer to use Angular Material going forward, this performance difference in IE10/11 is a deal breaker for our product. Any help or insight into this issue is much appreciated!

**PS:** I've also noticed in IE that when the ng-material demo page regains focus (e.g. click a different window then click back in), the page seems stuck and it often takes a while to scroll.

**Comment by brandon-shannon** [comment]
+1!

**Comment by codyhanson** [comment]
:+1:

**Comment by jmorales4** [comment]
+1

**Comment by aangoulvant** [comment]
+1

**Comment by wilkenstein** [comment]
+1

**Comment by ThomasBurleson** [comment]
@ross-nordstrom - Thank you for this information. Tomorrow we should have a release of Angular Material v0.8.3. Before our next milestone 0.9 release, we will address the IE11 performance issues... using your plunkr as starting points.

**Comment by ThomasBurleson** [comment]
@robertmesserle - it would be great if you had a chance to investigate this.

**Comment by schreinbo** [comment]
+1 Thanks!

**Comment by kschwidder** [comment]
I have the same experience when including the angular gantt within a tab in angular material.
When I started with 0.7.0 the response time was significantly better.
What I have discovered so far is that the $apply time is significantly higher in IE than chrome/firefox.
Does the material framework fires more $apply fragments ? Or is is a topic for the angular team ?

![performance chrome](https://cloud.githubusercontent.com/assets/3265624/6505012/f35bd42c-c33d-11e4-9b71-dad6c9f72fa6.png)
![performance ie](https://cloud.githubusercontent.com/assets/3265624/6505020/fcf377ce-c33d-11e4-8d81-25312f93da55.png)

**Comment by gkalpak** [comment]
<sub>(I would say it is more of a topic for the IE11 team :P)</sub>

**Comment by kschwidder** [comment]
Might be. Most enterprise customers are using IE on their desktops :-( If the apps are not performing well it has an impact.

**Comment by robertmesserle** [comment]
@ross-nordstrom Can you confirm that this is resolved for you?  Try the following files:

https://cdn.rawgit.com/angular/bower-material/v0.8.3-master-f62fd48/angular-material.js
https://cdn.rawgit.com/angular/bower-material/v0.8.3-master-f62fd48/angular-material.css

**Comment by robertmesserle** [comment]
Closing for now, please re-open if the issue persists.

**Comment by ross-nordstrom** [comment]
@robertmesserle That didn't fix it. I updated the [ng-material plnkr](http://embed.plnkr.co/E3chJw/preview) from before with the new versions above and am seeing the same issue in IE11 as described in my earlier post.

**Comment by bradmartin** [comment]
+1 / performance is quite terrible in an older ASP.NET app we have. And the ng-material demo site is sluggish as others have stated previously.

**Comment by arjendeblok** [comment]
+1 performance is also very slow on IE11 on Windows Phone 8.1. 
I will test LumX also to see if this has better performance on WP 8.1.

**Comment by borgdylan** [comment]
+1 , slowness also on mobile firefox for android on Nexus 7

**Comment by tinusn** [comment]
+1 Also experiencing this. Tried upgrading angular to 1.4.0-rc.1, but that did not have any effect.

**Comment by Aser17** [comment]
+1 I am also experiencing very poor performance on Firefox and IE11 using angular-material 0.9.0. Performance is, however, fine on chrome.

The issue must be somewhere in the CSS rules. My app relies on Google maps api, and just panning the map is very slow. I did a test and created a page with just a map, a few markers on it, and nothing else. As soon as I include the angular-material CSS file in my html page, performance suddenly drops. When panning the map without the CSS file included, IE11 says the minimum frame rate is 14fps (not great, but ok). when panning the map with the CSS file included, the minimum frame rate drops to 2fps (pretty much unusable).

**Comment by patriknyd** [comment]
+1 I see this on Firefox and IE11 in md-tabs. I have one tab with quite a
lot of content. Swiping to and from that tab is ok in Chrome but in Firefox
and IE the animation makes the CPU hit 100% for a while, like 4s for IE and
2s for FF. When the animation is finished everything is working again.

There should be a way to disable animation dynamically so I can turn it off
for bad browsers.

On Mon, May 11, 2015 at 4:24 PM, Aser17 <notifications@github.com> wrote:

> +1 I am also experiencing very poor performance on Firefox and IE11 using
> angular-material 0.9.0. Performance is, however, fine on chrome.
>
> The issue must be somewhere in the CSS rules. My app relies on Google maps
> api, and just panning the map is very slow. I did a test and created a page
> with just a map, a few markers on it, and nothing else. As soon as I
> include the angular-material CSS file in my html page, performance suddenly
> drops. When panning the map without the CSS file included, IE11 says the
> minimum frame rate is 14fps (not great, but ok). when panning the map with
> the CSS file included, the minimum frame rate drops to 2fps (pretty much
> unusable).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angular/material/issues/1771#issuecomment-100924575>.
>



-- 

/ *Patrik Nydensten*

**Comment by ThomasBurleson** [comment]
We recently fixed severe performance issues with our Jasmine/Karma testing. One of those changes included the need to disable Theme CSS Rule generation and `<style />` tag injections.

Grab the lastest build from #master on bower-material, and try this change as a quick test:

```js
angular.module('<YOURAPP>', ['ngMaterial'])
       .config(['$provide', function($provide) {
          /**
            * Angular Material dynamically generates Style tags
            * based on themes and palletes; for each ng-app.
            * Let's disable generation and <style> DOM injections. 
            */
           
           $provide.constant('$MD_THEME_CSS', '/**/');

        });
```

**Comment by tinusn** [comment]
I tried getting the master (angular-material@0.9.0-master-37cfe79) and tried with and without the provide setting, but it did not change anything for me.

I am mostly experiencing the problem in md-tabs with internal content. Chrome and firefox are fine both with and without animations for changing tabs, but IE is simply sluggish. Profiling reveals that IE is slower at handling the animation calls before the action (performAnimation -> beforeSetClass etc), but faster at the animation calls after the action (afterAnimationComplete).

Then I tried removing all content from the tab content and now IE is working as intended - so the solution for me might just be to optimize the content in the tabs.

**Comment by robertmesserle** [comment]
Tabs performance are being worked on as part of 0.10.0

I opened the following issue https://github.com/angular/material/issues/2821

You can track that for progress updates.

**Comment by kschwidder** [comment]
With the current build 0.9.4 I have recognized significant improvements of the performance across firefox, ie, chrome and safari too. Well done. Go ahead.

**Comment by demsey2** [comment]
I am working on a large enterprise app. We tried the latest 0.10.0  and still have serious performance issues. Chrome and FF look fine but IE11 is extremely slow. 

Angular-material.css includes layout attributes [layout=column] or [layout=row] etc. At the moment we don't use all features/components from material design so we had removed all layout attributes and IE11 started responding to simple click events (md-select, md-autocomplete). Here is a screenshot from IE11 dev tool where you can see how much time IE spends on recalculating styles, after we have removed all layout attributes from angular-material.css it dropped 10-15 times.
![style](https://cloud.githubusercontent.com/assets/3159367/8300494/d8d3aeea-19c8-11e5-832f-7891681ea896.PNG)

As I said before Chrome and FF works ok, I am not quite sure why IE11 works so slow.

We tried to find another material design service and compare in IE11. We visited and tried to use Google Trends https://www.google.com.au/trends/ and it is very slow as well. It looks like there are the same issues as we have in our service.

**Comment by sorba-ruben** [comment]
+1 I'm experiencing the same. It's horribly slow with IE11. How mentioned by the others, you can see it by opening https://www.google.com/trends/ with IE11. You can't really do a single click. You can also see it on https://material.angularjs.org/. It's not that horrible as on Google Trends, but still not very smooth.

**Comment by bradmartin** [comment]
Same, with some quick profiling I've noticed $digest cycles are just
cranking in IE for my app.

**Comment by gkalpak** [comment]
Could it be the issue with IE not combining multiple requestAnimationFrames ?

**Comment by Splaktar** [comment]
I've started to look at some of the ways that LumX differs from angular-material in these examples. Flexbox use/performance is my first concern due to the layout numbers above and my own personal experience. LumX does appear to have a less complex Flexbox system (http://ui.lumapps.com/css/flexbox). The flexbox CSS is here: https://github.com/lumapps/lumX/blob/master/modules/flexbox/scss/_flexbox.scss

I'll try to get some updated Plunker's later in the week with Angular 1.4.1 and 0.10.0. Then do some tests against those to hone in on the issue.

**Comment by rictorres** [comment]
sounds like a good starting point :)
thanks, @Splaktar

**Comment by ThomasBurleson** [comment]
@Splaktar - these should dramatically improve general performance on Mobile:

*  https://github.com/angular/material/commit/76cfd7066dd3e3bf6b8c51ee660442bbea8954ef
*  https://github.com/angular/material/commit/a9bc5345adeef87145f25624da7e4cd6ee4f3364

**Comment by cleever** [comment]
I have a feeling that IE's performance is very similar to mobile (chrome) performance. Including the issues.

**Comment by Splaktar** [comment]
The issues that @demsey2 noted about scrolling seem to be covered in #3455. I'm currently seeing pretty good performance on https://www.google.com/trends/ with IE 11 and MS Edge 20.10162.0.0.

That said, adding the 900 elements in the Plunker does still take about 6 seconds in MS Edge compared to about 1.5s in Chrome.

**Comment by mattclevyr** [comment]
How can this not be resolved yet?

**Comment by ThomasBurleson** [comment]
*  Animation performances have been improved
*  Tab performance has been significantly improved.
*  SideNav and Ripple perf improvements are in-progress and scheduled for 0.11

**Comment by mattclevyr** [comment]
@ThomasBurleson I appreciate that, and you and your hard work, but without significant speed/performance increases in IE we simply cannot use Material with enterprise clients who are locked into the Microsoft paradigm. 

Really excited about your upcoming release.

**Comment by timnix** [comment]
@ThomasBurleson We removed all of the media queries from the layout.scss and had performance gains in IE using Flexbox. So I guess IE is having trouble with all of the media queries.

**Comment by paulflo150** [comment]
I believe @timnix's suggestion has helped, but it's hard to tell since it's still very sluggish in IE11.

Any plans at all on making fixing the performance a top priority?

**Comment by bertramvarga** [comment]
WE found that the stylesheet size is what kills IE. So we are now compiling sass sources including only the used components and uncss-ing the unused layout selectors by scanning index + template files.
Using only about 10-15 components, the performance is almost equivalent to Chromes.
(I doubt this is good long-term solution but solves the problem for now.)

**Comment by timnix** [comment]
I played with this most of the day, trying to pinpoint what the issue is. I was just testing on IE10 but removing components did not have the same performance gain as removing things from the layout sass file. I ended up removing most of the media queries and any of the layout options that we are not using and taking out some of the animations on a few items. It was about a 3-4 second gain when navigating and clicking on a md-menu or md-select.

**Comment by paulflo150** [comment]
I have seen some speculation posted by someone on another issue that the performance may be affected by the attribute selectors, so I went ahead and changed the attribute selectors to classes in layout.scss, and created directives to add the corresponding classes, and IE 11 seems quite happy. I hope I am not breaking any licenses, but you can see it here: http://paulflo150.github.io/#/demo/material.components.select

Here is a comparison between attribute and class selectors for the select control:

![image](https://cloud.githubusercontent.com/assets/8136504/9400685/3dc380f4-4792-11e5-95cc-892113898cca.png)

![image](https://cloud.githubusercontent.com/assets/8136504/9400692/53f46438-4792-11e5-8d31-7e7c1b2dd657.png)

And here are my directives (hope I didn't mess anything up):
https://github.com/paulflo150/paulflo150.github.io/blob/master/tess-temp.js

and the css:
https://github.com/paulflo150/paulflo150.github.io/blob/master/css/layout.scss
https://github.com/paulflo150/paulflo150.github.io/blob/master/angular-material.css#L220

**Comment by ThomasBurleson** [comment]
@paulflo150  - This is a spectacular effort. Thank you. You should submit a PR for this and we will merge  within the main codebase..

**Comment by ThomasBurleson** [comment]
@paulflo150 - I created a PR and [Gist](https://gist.github.com/ThomasBurleson/cef20812dc8d12c7acfb) that shows a refactoring of your **layout directives**.

**Comment by cleever** [comment]
@paulflo150 - This is awesome!

**Comment by paulflo150** [comment]
@ThomasBurleson - thank you sir, the refactoring looks great! I will try to create a PR this evening. 

@cleever - thanks, all the credit goes to those who suggested class selectors were the answer. :)

**Comment by ThomasBurleson** [comment]
@paulflo150 - would you mind giving me a email ping: ThomasBurleson@gmail.com. Thx.

**Comment by timnix** [comment]
Great work! @paulflo150 & @ThomasBurleson, I reworked the gist Thomas created and got it working on the latest from here, I wasn't sure how to submit it to you guys since there was already a pull request from Thomas so here is the [Gist](https://gist.github.com/timnix/68cfbd6a170e484e6dea) i forked from @ThomasBurleson.

**Comment by ThomasBurleson** [comment]
@timnix - I liked your changes so much, I updated my PR to @paulflo150

**Comment by timnix** [comment]
@ThomasBurleson thanks! I was doing a little more tinkering, what are your thoughts on adding the hide and show attributes to this?

**Comment by ThomasBurleson** [comment]
@timnix  - let's see what you propose... in a GIST?

**Comment by timnix** [comment]
@ThomasBurleson Here is the updated [Gist](https://gist.github.com/timnix/68cfbd6a170e484e6dea) and thanks for the RegEx tip.

**Comment by paulflo150** [comment]
@ThomasBurleson  and @timnix thanks for all the help! I just submitted the PR.

**Comment by calebeaires** [comment]
+1

**Comment by kschwidder** [comment]
Amazing job !! The responsiveness has been significantly increased !
Thx

**Comment by ThomasBurleson** [comment]
Fixed with @paulflo150's PR #4282 and the commit SHA 46b5500c146c8d009809ccfae1014b98e1bbb79a

**Comment by ThomasBurleson** [comment]
@paulflo150 - care to regenerate the performance capture (for Select; as done above) with the latest code from master ?

**Comment by ThomasBurleson** [comment]
@kschwidder - plz try it now [with the latest updates on master] and http://material.angularjs.org

**Comment by paulflo150** [comment]
@ThomasBurleson - there is a slight difference, but from what I can tell that is because of the  navigation (not sure if there were any changes made to it the last few days). Other than that it looks good to me.

![image](https://cloud.githubusercontent.com/assets/8136504/9426206/a4b3cac6-48ff-11e5-8a9b-37b0a8a4e73d.png)

**Comment by stevenmiles** [comment]
Tested in http://codepen.io/stevenmiles/pen/MwNJWd and performance issue described in https://github.com/angular/material/issues/3455 went away.

Thanks @paulflo150 & @ThomasBurleson

**Comment by DOrlov77** [comment]
+1 the problem is here still... It's horribly slow with IE11. Just take a look on dialogs page demo:
https://material.angularjs.org/latest/demo/dialog
That issue should be reopened.

**Comment by Splaktar** [comment]
@DOrlov77 please open a new issue.

**Comment by parshotam** [comment]
md-tabs is very slow working.Following code i used 
<md-tabs md-no-pagination>

                <md-tab label="tab1" align="l" md-on-select>
                    <md-content class="md-padding">
                        <h1 class="md-display-2">Tab One</h1>
                        <div class="row">
                            <md-select class="col-lg-8 increasewd" name="tr_type" ng-model="tr_type" placeholder="select market"  aria-label="" required>
                                <md-option  ng-value="m" ng-repeat="m in lstMarkets" >{{m.name}}</md-option>
                            </md-select>
                        </div>
                        <div class="row" style="margin-top: 50px !important">
                            <md-select class="col-lg-8 increasewd" name="tr_type2" ng-model="tr_type2" placeholder="select market"  aria-label="Tariff" required>
                                <md-option ng-value="m" ng-repeat="m in lstMarkets" >{{m.name}}</md-option>
                            </md-select>
                        </div>

                    </md-content>
                </md-tab>

                <md-tab label="tab2"  md-on-select>
                    <md-content class="md-padding">
                        <h1 class="md-display-2">Tab Two</h1>
                        <div class="row">

                                <md-select class="col-lg-8 increasewd" name="tr_type" ng-model="tr_type" placeholder="select market"  aria-label="Tariff" required>
                                    <md-option ng-value="m" ng-repeat="m in lstMarkets" >{{m.name}}</md-option>
                                </md-select>

                        </div>
                        <div class="row" style="margin-top: 50px !important">
                            <md-select class="col-lg-8 increasewd" name="tr_type2" ng-model="tr_type2" placeholder="select market"  aria-label="" required>
                                <md-option ng-value="m" ng-repeat="m in lstMarkets" >{{m.name}}</md-option>
                            </md-select>
                        </div>
                    </md-content>
                </md-tab>

                <md-tab label="tab3" md-on-select>
                    <md-content class="md-padding">
                        <h1 class="md-display-2">Tab Three</h1>
                        <div class="row">
                            <md-select class="col-lg-8 increasewd" name="tr_type" ng-model="tr_type" placeholder="select market"  aria-label="" required>
                                <md-option ng-value="m" ng-repeat="m in lstMarkets" >{{m.name}}</md-option>
                            </md-select>
                        </div>
                        <div class="row" style="margin-top: 50px !important">
                            <md-select class="col-lg-8 increasewd" name="tr_type2" ng-model="tr_type2" placeholder="select market"  aria-label="" required>
                                <md-option ng-value="m" ng-repeat="m in lstMarkets" >{{m.name}}</md-option>
                            </md-select>
                        </div>
                    </md-content>
                </md-tab>
            </md-tabs>

In lstMarkets have a thousand records of markets. When i click the the second tab it take a more time to show the second tab . When i remove the <md-select> or ng-repeat in md-select options then it works fine. Have a any solutions  load the tab normally with all md-select options ?

**Comment by Splaktar** [comment]
@parshotam this issue is closed. Please post questions like this in the Angular Material forum on Google Groups. There is a link to the forums on the bottom of the getting started page.

**Comment by stevenmoberg** [comment]
I just saw this today with very large content and removed all css/js and added them back 1 by 1 to determine what was causing the issue.   jquery-ui.css slowed it down so I removed all its css and slowly add it back and found that the single ".ui-button:active" style was causing the issue even through I did not have any elements with this classname on the page.   I removed the ":active" selectors from my style sheets and I got the performance back.  It doesn't make any sense and I haven't seen any other reporting of this IE11 issue but thought it might help.
