### ISSUE TITLE
mdSelect: Autofill doesn't work

### ISSUE THREAD

**Issue by epelc** [angular/material#1801]
Autofill doesn't seem to work with `md-select`. Note the only thing I switched was `select` and `option` to `md-select` and `md-option` so it should still work.

![image](https://cloud.githubusercontent.com/assets/5204642/6514784/eca9d0a6-c339-11e4-9fb8-55bacb4c77f3.png)

Angular-material version: `0.8.3`
Browser: `Chrome 40.0.2214.115m Windows 10 64bit`

**Comment by naruraghavan** [comment]
I have the same issue - angular-material 0.8.3

![screen shot 2015-03-05 at 6 25 20 pm](https://cloud.githubusercontent.com/assets/688075/6517029/17ef4252-c365-11e4-900a-159a59bc7537.png)

**Comment by kschwidder** [comment]
I think that autofill only works if the item is bound to the ng-model. In my cases the items are objects therefore autofill will not work at all.

**Comment by naruraghavan** [comment]
Got it to show the ng-model... Looks like there is an alignment problem
![screen shot 2015-03-06 at 11 13 27 pm](https://cloud.githubusercontent.com/assets/688075/6540016/835ec818-c456-11e4-9e25-b34d8418e153.png)

**Comment by naruraghavan** [comment]
Never mind. Got it aligned with a ```margin-top```

**Comment by sathishvj** [comment]
@naruraghavan How did you get it to show the ng-model value when it first loads?

**Comment by breandr** [comment]
Could you share your html for mdSelect? How did you get the arrow aligned to the right. I've wrapped it in a flex div and added flex to <md-select> which pushes the arrow to the right, but it should probably just be styled like that for you, right? The examples in the docs just take up the width of the selected item or label

**Comment by epelc** [comment]
@breandr The picture was taken with `0.8.2`. The arrow alignment is broken in `0.8.3`. I remember seeing an issue for it but I can't seem to find it.

**Comment by breandr** [comment]
Thanks for that. I'll remove my approach and wait for the fix.

**Comment by rschmukler** [comment]
I've fixed the arrow alignment issue. Aside from that, is the original issue described here still valid? @epelc ?

**Comment by epelc** [comment]
@rschmukler I just checked in master and the auto fill still doesn't work. But +1 for fixing the arrow alignment.

**Comment by rschmukler** [comment]
@epelc cool, I'll take a look. With your `ngModel` and autofill, are you using a primitive or an object?

**Comment by epelc** [comment]
@rschmukler I think you'd call it an object? It's an object.primitive

```
<md-select flex ng-model="Address.Country" placeholder="Select a Country" ng-required="!simple">
            <md-option value="US">United States</md-option>
            <md-option value="CA">Canada</md-option>
</md-select>
```
