### ISSUE TITLE
md-select opens twice when ng-if and ng-disabled are combined

### ISSUE THREAD

**Issue by gustavohenke** [angular/material#1852]
When you have a `md-select` that combines `ng-if` and `ng-disabled`, it's opened twice when you click on it.

The same issue is observed when using `md-select` with only `ng-disabled` and a parent element with `ng-if`.

Example plunkr (just click in one of the selects):
http://plnkr.co/edit/IMPaUh9KhyUxAxvTleAO?p=preview

Demo gif:
![](http://i.imgur.com/JXn8yKL.gif)

**Comment by troch** [comment]
Same problem here, when ng-disabled is added (in my case there is no ng-if), the dropdown menu opens  twice.
Although, if the disabled attribute is present, md-select is styled but options can still be selected.

**Comment by troch** [comment]
The issue is because if md-select is initially not disabled (with ngDisabled), the $observe listener fires twice causing the click and key events listeners to be registered twice.

The solution (or hack?) is to track md-select disabled state and only register / de-register events if the disabled state has changed.

See pull request #1871

**Comment by MaximShoustin** [comment]
+1

**Comment by gustavohenke** [comment]
@MaximShoustin this is already fixed in 0.9.0.

**Comment by brunofin** [comment]
This issue still occurs with me on a **md-select** containing *ng-disabled* attribute with its **md-option** containing *ng-selected* attribute.

On AngularJS v1.4.6 and Angular Material Design v0.10.1

Example code:

```html
<md-input-container>
	          <label>Perfil</label>
	          <md-select ng-model="selectedProfile" ng-disabled="{{ isProfileEditable() }}"> <!-- ng-disabled="{{ !isProfileEditable() }}" -->
	            <md-option ng-repeat="_p in profile.profiles" value="{{ _p.id }}" ng-selected="{{ _p.id == profile.currentProfileId }}">
	              {{ _p.name }}
	            </md-option>
	          </md-select>
	    </md-input-container>
```
