### ISSUE TITLE
Material  + SystemJS load conflict 

### ISSUE THREAD

**Issue by brianfeister** [angular/material#1918]
I have a [seed project](https://github.com/brianfeister/angular-systemjs-seed) that uses Angular + SystemJS + oc Lazy load. The project works fine using ES6 dependency injection until I add Angular Material.  I get a `WARNING: Tried to load angular more than once.` I'm a bit confused about why this only happens when I inject Material `import 'angular-material';` in my main app.js bootstrap.

**Comment by epelc** [comment]
I think angular-material requires angular and might try to double load it. Try removing your angular injection.

**Comment by ThomasBurleson** [comment]
Fixed with recent changes in [Bower-Material](https://github.com/angular/bower-material). See readme for npm and jspm usages.

**Comment by chapati23** [comment]
not fixed for me.
using angular 1.4.7 and `jspm install angular-material@1.0.0-rc2`

load order is:
```
import 'angular';
import 'angular-aria';
import 'angular-animate';
import 'angular-bootstrap';
import 'angular-loading-bar';
import 'angular-material';
```

still get the warning

**Comment by rolandjitsu** [comment]
I still have this issue as well, if I import angular material I get that same warning.

**Comment by zakdances** [comment]
Still seeing this error too. I'm using `angular-material@1.1.0-rc1`. I'm importing it into my `app.ts` like this:

    import ngMaterial from 'angular-material'

it loads and seems to run fine, but throws 2 errors: `Cannot find module 'angular-material'` and `WARNING: Tried to load angular more than once.` I've tried removing all other angular-related imports but the warnings remain. The `Cannot find` error from Typescript makes me think something isn't being resolving correctly. All my other imports, Angular and non-Angular alike, are resolved without error. JSPM may be misinterpreting Angular Material's `package.json` somewhere.
