### ISSUE TITLE
Fix tap delay issues on iOS and older androids

### ISSUE THREAD

**Issue by ajoslin** [angular/material#195]
Fastclick? CSS fixes? Custom solution? Pointer events polyfill?

**Comment by ajoslin** [comment]
Done.

**Comment by ChristianWeyer** [comment]
@ajoslin where is this done? We have 0.9.0 rc1 and still have the delay.
If we add FastClick the md-button does not fire ng-click everytime...

**Comment by ThomasBurleson** [comment]
@ChristianWeyer  - We use [$mdGestures](https://github.com/angular/material/blob/master/src/core/services/gesture/gesture.js#L63) defined in Gestures.js

**Comment by ChristianWeyer** [comment]
Thanks @ThomasBurleson - but by default there is still a delay on iOS.
Is this a bug currently?

**Comment by ThomasBurleson** [comment]
Both Ionic and Angular Material attempt to resolve the iOS click/tap delay with custom gesture systems.
For more details regarding your issue, you would need to provide a CodePen or Plunkr that demonstrates this issue.
