### ISSUE TITLE
Unexpected behavior of md-dialog if back button is used

### ISSUE THREAD

**Issue by saulotoledo** [angular/material#1978]
You can easily note this at mobile devices, but you can try at normal browsers too.
Use the back button with a single page app back the page states, but the dialog still opened. The problems are (1) that some page states scroll the dialog outside the visible area when you press the back button, and (2) if you want to update some element at page who triggered the dialog, he is not there anymore, since the back button changed the angular's loaded page.

With mobile devices you can press the back button even by accident, leading to problems at pages.

The solution should be to close the dialog if the user press the back button.

**Comment by alanpurple** [comment]
+1

**Comment by epelc** [comment]
+1 If you hit the back button on a desktop the dialog stays open but the state changes. This is of course if your using ui-router.

**Comment by gustavohenke** [comment]
This should be implemented in the application.
The frameworks/libraries you use should not do magic.

**Comment by epelc** [comment]
It's quite easy to fix if you don't use special states to show your dialogs or have multi state dialogs.
```
 $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
  //Make sure you inject $mdDialog wherever you stick this
  $mdDialog.cancel()
})
```

**Comment by kugler** [comment]
@epelc this will close the dialog but the state will still change. Any idea on how to check if there is an open dialog? If there is, one could prevent the state change and only close the dialog.

**Comment by ThomasBurleson** [comment]
This is application-level logic with dependency issues upon Routing

**Comment by kugler** [comment]
@ThomasBurleson Maybe an addition of current state of $mdDialog / $mdSidenav / $mdBottomSheet would help. This way - on state change we could check the state and see if there is a dialog to close (and then prevent the state change). Something like $mdDialog.isOpen()

**Comment by ThomasBurleson** [comment]
@kugler - My comment on 8/10 was in error. Navigation may generate `$destroy` events and components that use interElements (eg bottomsheet, dialog, toast, menu, and select) need to properly cleanup during $destory cycles. This has been fixed in master with [SHA 77a34bd8](https://github.com/angular/material/commit/77a34bd8f122814527159d08536d5776b314f527)

**Comment by kugler** [comment]
Thanks @ThomasBurleson didn't know this was fixed - now we can remove another patch :+1: 
Let me explain our use case for the comment above: 
We use angular material for a responsive web app (desktop and mobile web) in addition to a hybrid mobile app. 
On android devices, users expect different behaviour when clicking the device's back button on a web page vs true mobile application. 
One of the things that would help emulate a real app is to enable closing dialogs on the device's back button (same as escape on a desktop keyboard) without navigating. We have the ability to catch the button click but in order to decide whether to navigate back in history or closing the dialog - we need to know the service's state (dialog open/close etc.).
I think this option will be useful in the future when multiple dialogs feature will be available.

**Comment by barryvdh** [comment]
I'm still having this issue;
When a md-dialog is opened, and I navigate with the back-button, the dialog stays open. It cannot be closed after that. But instead of changing the route, I just want to close the dialog

This can be fixed with a listener, but not sure if this is the best way

```js
$rootScope.$on('$locationChangeStart', function(event) {
    // Check if there is a dialog active
    if(angular.element(document).find('md-dialog').length > 0) {
        event.preventDefault(); // Prevent route from changing
        $mdDialog.destroy();  // Destroy the active dialog
    }
})
```

**Comment by barryvdh** [comment]
Ideally it would probably remember the stack of dialogs, perhaps even change the url state, and close the dialogs in order.

**Comment by rvarbanov** [comment]
Same here, still a bug.

**Comment by smurugavel** [comment]
+1

**Comment by kssaw** [comment]
@barryvdh The solution you provided solved my problem. Thanks!!!

**Comment by BeSaRa** [comment]
@barryvdh thanks for your answer , it is very helpful

**Comment by grrrian** [comment]
we can simplify @barryvdh suggested answer to: 
```
$rootScope.$on('$locationChangeStart', function($event) {
      // Check if there is a dialog active
      if ($mdDialog.isShowing()) {
        $event.preventDefault(); // Prevent route from changing
        $mdDialog.cancel();  // Cancel the active dialog
      }
    });
```

**Comment by sthan001** [comment]
How to handle close dialog on outsideclick and escape along with state change ?

Back button  click to close dialog along with url change result in UI router state change.
But when users click outside dialog it has to be closed along with bring same similar behavior of back button press.

What is best way to handle above two scenarios?

**Comment by rafaeldev** [comment]
@grrrian the function isShowing doesn't exists for me. I'm use the latest version of Ang Material.

I put your example code on `module.run` method where I inject the $mdDialog. It's Correct?

**Comment by colmben** [comment]
@rafaeldev Looking at the code, there is no isShowing. And logically I think they would go with isOpen - this is discussed in this issue https://github.com/angular/material/issues/5071 , which also has an alternative method for checking for an open dialog:

angular.element(document.body).hasClass('md-dialog-is-showing')

which will presumably be quicker than doing a find for an md-dialog.

**Comment by rafaeldev** [comment]
Thanks @colmben for your answer!
