### ISSUE TITLE
Subheader positioning and sizing issue

### ISSUE THREAD

**Issue by krassx** [angular/material#2056]
Take a look at this screen shot:

https://www.dropbox.com/s/kfkp8uc3ptnefax/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202015-03-28%2001.15.35.png?dl=0

It was made on official website. I just changed background from white to green and got all those gaps that look really weird. In my project I have tiled images grouped by some criteria that's why I do not have white background, but I do have subheaders in that list. And when I scroll the list those gaps are all visible and annoying. Is there any way to fix this? Really don't want to use "hacks" to fix that just for myself. I am sure there is more natural way to make it in the framework itself. Thanks in advance.

**Comment by marcysutton** [comment]
Sounds like an issue with $mdSticky.

**Comment by elrabelo** [comment]
I think this was corrected here: https://github.com/angular/material/issues/708, but it wasn't merged, I suppose.

**Comment by krassx** [comment]
Checked the state of this issue with 0.9.0 and it still reproduces easily:

http://gyazo.com/0c037841518bcc12a9e2c0a834b8f88b

**Comment by TylerEich** [comment]
I'm also having this issue with 0.9.0

![image](https://cloud.githubusercontent.com/assets/3460063/7506942/9279903a-f435-11e4-82a0-3fe5b71fa034.png)

**Comment by ThomasBurleson** [comment]
Please provide a CodePen or Plunkr that demonstrates this issue. Here are some starter demo templates that you can use/fork:

*  CodePen template: http://codepen.io/team/AngularMaterial/pen/BNYppz
*  Plunkr template: http://plnkr.co/edit/yP0gB9iTacIQb48thud8?p=preview.

**Comment by Todd-Werelius** [comment]
Looks like 2 issues

1. A gap between header 1 & 2 shows the background color, looks like the shadow of the top most header should be turned off when the second header bumps into it [Codepen](http://codepen.io/Mopholo/pen/pjBJre)

2. He is having the issue with the sticky [pr #1151](https://github.com/angular/material/pull/1151) which you can see with parent left/right padding, which I also added into this pen
