### ISSUE TITLE
md-select broken in build when inside md-content element

### ISSUE THREAD

**Issue by hodeyp** [angular/material#2379]
looks like an md-content with a layout attribute causes the select to do weird things...

http://plnkr.co/edit/vAaWq8r1zIgmMnouwHij?p=preview

**Comment by epelc** [comment]
+1 I definitely can't use `0.9.0-rc1` until this is fixed.

I looked into it a bit and It seems the following styles are added to the first div within `md-content`. Removing them fixes `md-content` being expanding horizontally causing a scroll bar.
![image](https://cloud.githubusercontent.com/assets/5204642/7202303/ffb0e57e-e4de-11e4-8d82-b9a1e22cfd11.png)
For formatting's sake here they are in text
```
  overflow: hidden;
  position: fixed;
  width: 100%;
  padding-top: 0px;
  top: 64px;
```

**Comment by epelc** [comment]
The select positioning and width are fine if you do not have any `layout` attibutes on or between your `md-content` and your `md-select`. However it still adds the css in my above comment which breaks `md-content`s width.

**Comment by epelc** [comment]
This also really breaks `md-select` if you use it in a dialog.
![image](https://cloud.githubusercontent.com/assets/5204642/7202913/b844c312-e4e4-11e4-9004-5805bb5b2af7.png)

**Comment by loykianos** [comment]
I seem to be having the same problem, even without any layout attributes.

![capture](https://cloud.githubusercontent.com/assets/4227423/7203255/a2b726b8-e519-11e4-83fe-cb8ef9fcb249.JPG)

**Comment by rschmukler** [comment]
@epelc have you tested on master yet? If not, can you give it a go and see if it's resolved.

**Comment by hodeyp** [comment]
this is definitely still an issue on master

**Comment by epelc** [comment]
@rschmukler Just checked same problem. I'll be on gitter if you want any help debugging

**Comment by rschmukler** [comment]
@hodeyp and @epelc working on it now, should have something soon. Sorry for the bug. Disabling scrolling in a consistent, cross browser compatible way, is bit tricky.

**Comment by hodeyp** [comment]
@rschmukler hate to disappoint but still not working - my original plunker above still suffers from disappearing elements when the select is shown.

**Comment by loykianos** [comment]
I also tried to update and I still have weird template reactions when opening the selectbox. See bellow.

Before:
![before](https://cloud.githubusercontent.com/assets/4227423/7215706/04dc6554-e5e4-11e4-8bb8-0dc56e35af6a.JPG)

After:
![after](https://cloud.githubusercontent.com/assets/4227423/7215707/10e493b2-e5e4-11e4-9d0c-130bdd36b496.JPG)

**Comment by epelc** [comment]
Try using master so you get @rschmukler's fix

**Comment by loykianos** [comment]
I am, and I updated a few hours ago. Tried again just now, same result.

**Comment by ThomasBurleson** [comment]
@loykianos - Please provide a CodePen or Plunkr that demonstrates this issue.
@epelc, @hodeyp  - have the fixes in #master resolved this issues for you?

**Comment by loykianos** [comment]
There you go, http://plnkr.co/edit/j8RqpRtNnzAyKjX3DnC8?p=preview

Still having the same problem with no extra CSS added.

**Comment by epelc** [comment]
@ThomasBurleson This fixed all of my problems besides one but I found a work around.

I had a class which adding `padding-left/right: 5%` on my `md-content` for larger devices but it caused my fab button to be cut off graphically whenever I opened a select. I fixed it by adding `margin-left/right: 5%` to my `md-card`'s instead which gave me the same padding/margin effect.

**Comment by hodeyp** [comment]
sorry, still not working for me, and the plunker still shows the same issue.

http://plnkr.co/edit/vAaWq8r1zIgmMnouwHij?p=preview

**Comment by epelc** [comment]
@ThomasBurleson I just noticed `$window` isn't firing `resize` events after I open and close an `md-select`.

**Comment by FelAmine** [comment]
I'm having this issue with version 0.9.0-rc1 but not with 0.8.3.

**Comment by jsteenkamp** [comment]
Broken in dialog on #master. Removing md-content provides workaround but is contrary to md-dialog docs that say you should use md-content.

**Comment by Tyrannmisu** [comment]
Master is still broken for me in Firefox and chrome, it breaks the layout when used in dialogues and also breaks $window.resize listeners.

The Layout was okay in master-f3c113c (but it still broke the listeners) when using chrome, now its broken in Firefox and Chrome (even though the results are a bit different.)

In Firefox the elements in the dialogue are all over the place (outside the dialogue) when opening the select and the actual select is above the dialogue. In Chrome the dialogue becomes empty and the select is shown on the right side outside of the dialogue.

0.8.3 worked mostly fine, only Firefox showed some scrollbars on the body while opening the md-select.

**Comment by albertosantini** [comment]
Another codepen example not working by @Alexandre-io is the following one: http://codepen.io/Alexandre-io/pen/WbVWKP

Tested with v0.9.0-rc1-master-aff50d5 and it doesn't work.
https://github.com/angular/material/issues/2350#issuecomment-94085750

**Comment by rschmukler** [comment]
Thank you everyone for the detailed examples. Looking into it and getting something ASAP!

**Comment by epelc** [comment]
@rschmukler I just noticed the new way you handle disabling the side bar causes content to expand the size of the scrollbar while the select is open. I think it needs margin-right to counter act this if you open the select within `md-content`(and possibly in dialogs but I haven't checked). Also this happens because the scrollbar is removed when the select is open now.

**Comment by rschmukler** [comment]
@epelc it should be wrapping the outer element with an `overflow-y: scroll` which should create a scroll bar on the outer element. What browser / OS are you using?

**Comment by epelc** [comment]
@rschmukler I'm using windows 10. I've testing in chrome 42.0.2311.90 m and firefox 36.0.4/37.0.1

![image](https://cloud.githubusercontent.com/assets/5204642/7233840/736381d8-e751-11e4-80d9-abc76a307cbe.png)

It only seems to happen if the select is within `md-content` as my select on my toolbar doesn't have this issue however it also doesn't ever have a scrollbar.

**Comment by epelc** [comment]
@rschmukler The use of a container `div` with styles is also breaking any child css selectors ie `md-content > .someClass` will break because `md-select` injects a `div` with some styles on it between `md-content` and your element with `someClass` on it.

![image](https://cloud.githubusercontent.com/assets/5204642/7235079/cf527c1c-e759-11e4-982f-a8f255f11d49.png)


I also noticed if you scroll down and open a select near the top of your screen within md-content then it cuts off the bottom of your md-content. I think this is why my fab was getting cutting off from the bottom sometimes after I applied my workaround for the padding-left/right.

![image](https://cloud.githubusercontent.com/assets/5204642/7235181/6e9d6192-e75a-11e4-9e52-a90c74d8ba21.png)

**Comment by epelc** [comment]
@rschmukler Removing the `top: -193px;` from the div that gets injected with the css in the style attribute seems to fix the second issue above with the bottom getting cut off.

**Comment by rschmukler** [comment]
@epelc , @albertosantini and @hodeyp please give the latest master build a go.

Dialog should be working, as should the demos in the code pens above. Please let me know if it's working well in your application.

@epelc regarding the child selectors, there's not much that can be done. I could copy classes from parent, but I anticipate that that'd create more bugs than it'd solve. Let me think on it, but it's separate of this issue in either case.

**Comment by hodeyp** [comment]
sorry @rschmukler still an issue in my app. my plunker above also still displays the same issue. Basically if the md-select is inside an md-content container the container itself disappears when the select is open. Looking at chrome debugging my standard html has an md-toolbar and a few layout div siblings. the md-select is within the md-content which is a child of one of the layout divs. When the select is opened, the toolbar & content is wrapped in a div...

```
<div style="max-height: 1132px; height: 100%; overflow: hidden; position: fixed; display: flex; align-items: stretch; justify-content: flex-start; flex: 1 1 0%; padding-top: 0px; margin-top: 0px; margin-left: 0px; top: 0px; left: 0px; width: 100%; max-width: 1496px;">
```

this makes the toolbar go to 100% height and the md-content and all children go to 0px width.

**Comment by rschmukler** [comment]
@hodeyp regarding your original plunker. I just tested it and got [these results](http://files.slingingcode.com/2r0q322H2B2k/Screen%20Recording%202015-04-20%20at%2001.52%20PM.mov). What browser are you using? Are you sure your cache has been cleared?

**Comment by albertosantini** [comment]
@rschmukler Great job. 

For me the dialog is completely ok. 

The only glitch is the display of the scrollbar when the select is opened: this is select is not contained in the dialog.

**Comment by rschmukler** [comment]
@albertosantini regarding the select scrollbar display, can you post a screenshot of what you mean? Also, windows or mac?

**Comment by hodeyp** [comment]
@rschmukler - darn that browser cache. Killed my browser and re-opened, all is well!! Thanks for sorting that one out :)

**Comment by rschmukler** [comment]
@hodeyp no problem! Super happy to hear that it's working for you. I was concerned that'd it was going to be harder to track down if it was browser dependent haha. Glad to hear that it's working. Please let me know if you run into more issues so that I can fix them.

**Comment by hodeyp** [comment]
sure thing, I use md-select heavily across the app so will be able to give it a thorough test out.

**Comment by albertosantini** [comment]
On Windows with Chrome 42.

With select opened no scrollbar at the right.
![image](https://cloud.githubusercontent.com/assets/328179/7236983/b13e9082-e798-11e4-8a9b-254e084942ca.png)


With the select opened (see the scrollbar at the right).
![image](https://cloud.githubusercontent.com/assets/328179/7237009/cbc0164c-e798-11e4-91fd-b22c0f4b6592.png)


(I tried with IE11: the dialog is a nightmare, but it is not related with the select)

**Comment by hodeyp** [comment]
hey @rschmukler i've discovered another issue, layout is working fine on all of my md-selects but there was one of my views that when I clicked on the select the entire app locked up and chrome displayed the aww snap dialog. I have managed to identify it has something to do with an md-content being a child of a form. When I remove the md-content the select works fine, and if the form is a child of the md-content it is also fine. It is only if the md-content is the child of the form. Sounds a bit weird so maybe i'm barking up the wrong tree but it is repeatable, want me to plunkr?

**Comment by rschmukler** [comment]
@hodeyp does it work in Firefox with the nested md-content in the form? If so, I suspect it might be a chrome bug.

**Comment by hodeyp** [comment]
@rschmukler no doesn't work in firefox either.. tells me the issue with with angular-material.js:890

**Comment by epelc** [comment]
@rschmukler I just checked with latest master and the md-content being cut off still happens.

**Comment by rschmukler** [comment]
@hodeyp fixed, thanks!

**Comment by rschmukler** [comment]
@albertosantini Does the page scroll when the select is closed? ie. is it longer than the window size? Or is there no scroll bar on that page?

**Comment by rschmukler** [comment]
@epelc can you give a plunker of the cutting issue you're experiencing.

**Comment by albertosantini** [comment]
@rschmukler The page doesn't scroll. 

It is not longer than the window size.
When I close the select, the scrollbar disappears.

In my css I have

```
body {
    overflow-y: hidden;
}
```

**Comment by epelc** [comment]
@rschmukler It seems to be caused by having `layout="column"` on bother `body` and `md-content`. Removing it from either one seems to fix it.

Here's a plunker
http://plnkr.co/edit/44McFB0VzbTSGSfbKjAy?p=preview

I guess it's not too important it's an easy workaround depending on how your app is layed out. Anyways I can live with it.

**Comment by rschmukler** [comment]
@albertosantini thanks for helping me find that one. Fixed by b9ee6121412d59895b43286f4eefd4418e9081aa.

@epelc taking a look now!

**Comment by rschmukler** [comment]
@epelc Looks like it might be a rawgit caching issue. The nested column example (with the code from the plunker you posted) looks like it's working for me on my locally built version. Let me know if this isn't the case for you.

**Comment by epelc** [comment]
@rschmukler Did you scroll down then open the select? I have disable cache on in chrome. If not can you post your locally built one so I can add it to the plunker?

**Comment by rschmukler** [comment]
@epelc just tried it with locally built on plunker. Oddly enough it breaks... But it doesn't break when I test it locally with the same code that breaks the plunker. I'll poke around a bit more.

**Comment by albertosantini** [comment]
@rschmukler Job done! :) All fixed (with Chrome) here. Thanks a lot.

**Comment by Tyrannmisu** [comment]
@rschmukler : Works fine now in Firefox and chrome, thanks ! :)

**Comment by jgoux** [comment]
Almost there !
I have still a bug when I have multiple md-content with one in scroll mode : 
![select](https://cloud.githubusercontent.com/assets/1443499/7259332/d48e4c88-e862-11e4-9431-1d6d88a989e6.gif)

As you can see all the content of the scrollable md-content is going out of its parent.

**Comment by ayastreb** [comment]
There is a strange thing, which makes my Chrome freezing and crashing, if I surround md-select with <div> tag.
This example works ok - http://codepen.io/anon/pen/ZGEQGM
And this one makes the chrome freeze when I click on md-select - http://codepen.io/anon/pen/vOYLNL
Same happens on Mac Safari.
It only happens if the md-select is inside <form> tag - if I remove form - it works ok.
Is it reproduced for anyone else?

**Comment by epelc** [comment]
@ayastreb I can confirm that on chrome 42.0.2311.90 m windows 10 preview

**Comment by jgoux** [comment]
@ayastreb Wow me too. I assume there is an infinite loop somewhere. oO

**Comment by Tyrannmisu** [comment]
Just realised that the select seams to break my $window.resize listeners with 0.9.0rc2 again.
Not sure if it's still broken or was fixed before :-/ .
Using them in a dialogue with md-content.
The issue is present in Firefox and chrome. 

After a a select is opened watch events like this don't fire anymore:

```javascript

angular.element($window).bind('resize', function () {
    //...
});

```

**Comment by epelc** [comment]
@Tyrannmisu It wasn't fixed yet. It is broken in `0.9.0-rc1` and rc2

**Comment by Tyrannmisu** [comment]
@epelc good to now, same thing in latest master by the way.

**Comment by rschmukler** [comment]
@ayastreb I have fixed the loop issue you mentioned, it's fixed on master. Looking into other issues now. Once they are resolved I am going to close this issue and potentially re-create separate issues on github as this has become a bit of a catch-all for select issues, making it harder for me to prioritize

**Comment by ayastreb** [comment]
@rschmukler thank you! Fixed now.

**Comment by rschmukler** [comment]
Disable scroll is now implemented via a virtual scroller, which should help. @epelc your clipping issue should be resolved with the latest, as well as @jgoux 's layout issue.

I'm closing this issue to help with tracking. Please create a new issue for any new/remaining layout bugs.

Thank you again everyone for helping me track down all of these use cases.
