### ISSUE TITLE
Input is disappearing on iOS (version 0.9.0-rc2)

### ISSUE THREAD

**Issue by cosmin-petrescu** [angular/material#2520]
Hello,

Seems to be a problem on iOS with the input from an md-input-container. While you write in it (or deleting from it) the bottom border and the text is disappearing.
The problem persist from 0.9.0 until rc2.

**Comment by ThomasBurleson** [comment]
Where are you seeing this? In you custom application or our online Docs ?

**Comment by cosmin-petrescu** [comment]
First on my app (made with Ionic), after that I tested in https://material.angularjs.org/ from my iPhone 5 (iOS 8.3). Also, my colleague tested on an iPhone 6 with iOS 8.3.
Seems on iPad with iOS 7.1 works fine.

**Comment by royvandewater** [comment]
+1

**Comment by ThomasBurleson** [comment]
Should be fixed with SHA f1df6dc09c20635d42ffaada32ae2f036666a5ba and SHA ea817874b0b46fbae883e5191b234d1d4e38179c. Can you confirm this is fixed with latest commits in #master ?

**Comment by cosmin-petrescu** [comment]
I tested in 0.9.0 release (demos) and seems to be fixed in there. Thanks for your support.

**Comment by BirdInTheCity** [comment]
I'm still seeing this issue on both an iPad Air 2/iPhone 6 in Chrome/Safari on the current master build (0.9.0. SHA C767FD2) when previewing the demos.  Not sure if it's a problem with the demo site or the components themselves.  I made a video of it for reference:  

https://www.youtube.com/watch?v=7bU7bL1Gxvs
