### ISSUE TITLE
ng-messages doesn't hide when input is valid

### ISSUE THREAD

**Issue by smehrbrodt** [angular/material#2781]
The message should be hidden once there is some input in the field.

![bildschirmfoto vom 2015-05-08 11 51 53](https://cloud.githubusercontent.com/assets/3502738/7534239/03599914-f579-11e4-8d3b-f98f7292cdd1.png)
![bildschirmfoto vom 2015-05-08 11 50 50](https://cloud.githubusercontent.com/assets/3502738/7534241/07a759d4-f579-11e4-97c2-a180e0e81077.png)

**Comment by smehrbrodt** [comment]
I found out that when using `<ng-message>` as element instead of an attribute, it works as expected:

```html
  <md-input-container flex>
    <label translate>First Name</label>
    <input name="firstName" ng-model="person.firstName" required>
    <div ng-messages="personEdit.firstName.$error">
      <ng-message when="required" translate>This field is required.</ng-message>
    </div>
  </md-input-container>
```

Is this a material or angular bug?

**Comment by mafredri** [comment]
It's not entierly obvious when reading the documentation, but you need `ngMessages` for errors, as can be seen here: https://material.angularjs.org/#/api/material.components.input/directive/mdInput

**Comment by smehrbrodt** [comment]
That was the problem, many thanks for the hint!

**Comment by JobaDiniz** [comment]
It is not working here... I'm using `<div ng-messages="expression"`

**Comment by brianmuks** [comment]
This "ng-message" is used as an attribute on angular material demos https://material.angularjs.org/latest/demo/input

**Comment by ady236** [comment]
I had similar issue. I just added ngMessages dependency in module in app.js. Solved my problem.

**Comment by danillobarbosa** [comment]
Just add ngMessages directly in your module.

This works.

 :)

**Comment by yongolan** [comment]
Fixed my issue too - thank you!

**Comment by mostafabarmshory** [comment]
Fixed my issue too, thank you very much

**Comment by AlekseyChuyan** [comment]
Why Not add this part to documentation?

**Comment by brunneus** [comment]
I still have this problem, I've already inject "ngMessages" on my app and still not working, any other solution?

**Comment by marcoskubis** [comment]
Sometimes I also don't read all.
![capturar](https://cloud.githubusercontent.com/assets/3844716/18480919/c8a67cb6-79b0-11e6-86ae-6921daa09eb6.PNG)

**Comment by mcianc** [comment]
Same issue resolved like told by 
smehrbrodt commented on 8 May 2015

Using element instead attribute all work like a charm

**Comment by derek1906** [comment]
It is also stated in [the documentation of `ng-input`](https://material.angularjs.org/latest/api/directive/mdInput):

>## Notes:
> - Requires ngMessages.
- Behaves like the AngularJS input directive.

**Comment by ersingencturk** [comment]
this definitely should be highlighted better in the documentation.how about a <h1> tag to the explanation?

**Comment by Splaktar** [comment]
This is now also part of the `blank shell` CodePen in the "Getting Started" Guide and there is a section in the same guide that [breaks down the optional dependencies](https://material.angularjs.org/HEAD/getting-started#installing-the-angularjs-material-libraries).
