### ISSUE TITLE
Dangling md-subheader and md-toolbar

### ISSUE THREAD

**Issue by nobarany** [angular/material#2825]
When a md-toolbar with md-scroll-shrink shrinks, the following subheader or md-toolbar doesn't move up to the top of the page, and it just dangles in the middle.
This codepen shows the problem for subheader, which appears only in Chrome (related to issues #1647 and #1726):
http://codepen.io/anon/pen/rVeaaL

But the problem with a second toolbar happens in Firefox as well:
http://codepen.io/anon/pen/QbNwQj

Interestingly, by adding md-scroll-shrink to the second toolbar you can achieve the behavior that you'd expect from the above code (i.e., the second one doesn't shrink). 
http://codepen.io/anon/pen/MwyYvj

**Comment by topherfangio** [comment]
@nobarany I just pushed some code that ***might*** fix this problem and will be available in 0.11. When it lands, could you try it out and see if it solved your problem?

**Comment by topherfangio** [comment]
Can you please provide a demo using the latest master code about exactly what you are attempting to accomplish?

I believe your first issue has been addresses, but I'm not exactly sure what you're wanting your second and third demos to do.

**Comment by nobarany** [comment]
In the second demo, there are two toolbars: the first one is supposed to shrink as user scrolls down and the second one is supposed to stick to the top of the page. It still doesn't work (with the latest master code from gitcdn.xyz):
http://codepen.io/anon/pen/EVeEgb

**Comment by topherfangio** [comment]
Okay, so I think you have three options here:

1. Toolbar 1 Stays Visible and Toolbar 2 Shrinks - I don't think you need `md-scroll-shrink`. Just put the second toolbar inside of the `md-content` like this: http://codepen.io/topherfangio/pen/epLKmq

2. Toolbar 2 Stays Visible and Toolbar 1 Shrinks - You can put the toolbars side-by-side and put the `md-scroll-shrink` on the Toolbar 2: http://codepen.io/topherfangio/pen/EVeRjj

3. A variation of #2 - You put `md-scroll-shrink` on both and it still does the same as #2, but it gives a slightly different "push" effect rather than the "cover" effect: http://codepen.io/topherfangio/pen/zvJaBG

Do any of those meet your needs, or are you trying to do something else?

In general, the `md-content` has really only been designed to work with a single `md-toolbar`, so anything outside of that is probably going to require some customization.

**Comment by nobarany** [comment]
# 2 and 3 works for my needs. Thanks! But they shouldn't! The expected behavior is that the toolbar with md-shrink should shrink, not the other one. Am I missing something?

**Comment by topherfangio** [comment]
The toolbars with `md-scroll-shrink` use a CSS transform to modify the position of the toolbar and make it disappear. So, it's not *actually* moving the toolbar anywhere.

So, using `md-scroll-shrink` on just Toolbar 1 does in fact do the intended (albeit strange) behavior because the component isn't actually moving and causing the page to re-flow and re-position/move Toolbar 2 upwards.

Since the most common case was to handle a single toolbar, that is what we optimized for. If we see a lot of people using it in a different manner, we may consider altering this and/or adding a new option.

If this is something you would like to see, could you please open a new issue with a description and ideally a video or Codepen of the effect you are wanting to create?

Since the original subheader issue is fixed, and we have a workaround for the second, I am going to go ahead and close this issue.

**Comment by nobarany** [comment]
It works for me, thanks.
