### ISSUE TITLE
md-menu: not opening/closing menu and showing md-menu-content without clicking

### ISSUE THREAD

**Issue by ruben1** [angular/material#3326]
So, I have this code that is very similar to the example on the documentation. The problem is there's no errors in my console and it's not working. It doesn't open or close the popup. Also, the content of md-menu-content is not hidden. 
```
<md-menu>
  <md-button ng-click="$mdOpenMenu()" class="md-icon-button" aria-label="Open sample menu">
    <md-icon md-menu-origin md-svg-icon="./assets/images/sensor_icon.svg"></md-icon>
  </md-button>
  <md-menu-content>
    <md-menu-item><md-button ng-click="vm.goThere()">Do Something</md-button></md-menu-item>
  </md-menu-content>
</md-menu>
```

**Comment by mukilane** [comment]
The menu is working correctly. 
http://codepen.io/anon/pen/BNwyrB (Just replaced the icon)

**Comment by ruben1** [comment]
Nice. It must be something in my app then.

**Comment by ruben1** [comment]
It was actually a bug from Angular Material. Update to version 0.10.0 to fix it

**Comment by ruben1** [comment]
It still has a weird behaviour. It works perfectly when it's alone in the page. But sometimes the positioning of the popup menu is not done right. I'll check out the code to see what might be the problem.

**Comment by mukilane** [comment]
Well, the menu component is added in v0.10.0. It won't be supported in the previous versions. 
https://github.com/angular/material/blob/master/CHANGELOG.md

**Comment by ruben1** [comment]
Cool. But still, I have some problems with the positioning. I'll look into
it now

**Comment by ruben1** [comment]
So, something was conflicting with the popup menu appended to the body. I changed the parent container to another element located inside the body that contains all my site and it's fixed. 

The problem was that the 'top' css property of the popup menu appended was set to a large negative number(ex: -500px). It must be something on my site that mess up the calculations for the positioning but I guess it can happen to other sites so it's worth to look into

**Comment by atinder90** [comment]
having same issue.
top is very high negative value.
How do you set the parent ?

**Comment by ruben1** [comment]
https://github.com/angular/material/blob/master/src/components/menu/menu-interim-element.js#L80 
I changed it to the closest children of body and it calculated the top correctly. 

btw, the large negative value on top is applied somehow here https://github.com/angular/material/blob/master/src/components/menu/menu-interim-element.js#L101

Do you have any fixed elements on your page?

**Comment by atinder90** [comment]
no i don't think so.

how do you pass the optional parent argument ?

I tried using 
<pre>
<md-menu parent="mySelector">
-----
</md-menu>
</pre>

but didn't worked.

**Comment by danieladz** [comment]
I'm also having Ruben's problem, to show the menu I added a style, but I don't like it that way, I can't find what is interfering with the menu :disappointed:

**Comment by vivekimsit** [comment]
I'm also facing the same issue, the popup position is not correct. Maybe we are missing some documentation here.

**Comment by danieladz** [comment]
I tried with this 
 <md-menu-content style="position: fixed; right:10px; top:64px;">
this helps me to show it, but all the options are shown in the same line, and it's awful this way,

**Comment by danieladz** [comment]
fixed, at least for me, we had, for some strange reason, a copy of and old angular-material css
:100:

**Comment by vivekimsit** [comment]
Fixed on my side too :+1:

**Comment by juliusl** [comment]
This was causing issues for me when I had a table with a good number of elements. Eventually when I do this:
```
      //clamp(position);

      el.css({
        top: Math.abs(position.top) + 'px',
        left: position.left + 'px'
      });
```
Everything just works. I think there might be an issue in the clamp() logic.

https://github.com/angular/material/blob/master/src/components/menu/menu-interim-element.js#L363

**Comment by sunnypatel** [comment]
That fix worked for me, however some elements on the page still get the top: -500px property and get lost on the page.  Does anyone have a solution for this?

**Comment by mohdsalmanshaikh63** [comment]
I wasted one in trying to make mdMenu work but later I opened the codepen and pasted the code in my html template to surprisingly find it working. I noticed that it had **$mdOpenMenu()** while on the official documentation which is found here `https://material.angularjs.org/latest/demo/menu` has **$mdMenu.open($event)**. Don't know but maybe this is due to some version difference. Hope you guys correct it.

**Comment by Splaktar** [comment]
@mohdsalmanshaikh63 you didn't provide any information on the version of AngularJS Material you are using. However, in [this commit](https://github.com/angular/material/commit/1e4ba35d4d7b3ec15b482863a6d60def1b760117) the `$mdOpenMenu` method was deprecated. This landed in `1.1.2`. You should see a warning in the console if you use it due to: https://github.com/angular/material/blob/master/src/components/menu/js/menuController.js#L241-L245.
