### ISSUE TITLE
md-fab-speed-dial: does not animate the first time

### ISSUE THREAD

**Issue by lboekhorst** [angular/material#3349]
In angular-material v0.10.0, the `md-fab-speed-dial` component does not animate the first time it is hovered or touched. The embedded example on https://material.angularjs.org/latest/#/demo/material.components.fabSpeedDial works properly, but the supplied CodePen has the same issue. This occurs in Chrome 43 and Internet Explorer 11. I have not tested other browsers.

When the action buttons are hidden, the `.md-fab-action-item` does not have its `transform` property set before it is activated. After it has been activated, it has. The embedded example has its `transform` property set before it is even opened for the first time, so that might be what's going wrong.

**Comment by relevantmedia** [comment]
I am having the same problem. Is there something else we are missing.

**Comment by relevantmedia** [comment]
I looked again and realized that I did not update my css file when I updated the script to 0.10. Once I added 0.10 of the css file as well then it worked for me.

**Comment by lboekhorst** [comment]
Good to hear! This did not fix it for me though, I'm still having the same issue.

**Comment by topherfangio** [comment]
Hi guys, I will take a look and see if I can figure this out. I had experienced this a few times in the past, but I thought it was an issue with the automatic browser reload I was using because I could refresh the page and it went away. Perhaps it is a timing/initialization issue.

**Comment by lboekhorst** [comment]
Great, thanks!

**Comment by ronyrun** [comment]
Hello, 

I'm having the same issue currently. ("version": "1.0.6")
 the `md-fab-speed-dial` component does not animate the first time it is hovered or touched.
