### ISSUE TITLE
md-fab-speed-dial does not work correctly for up/down in Safari

### ISSUE THREAD

**Issue by Sayene** [angular/material#3375]
None of the examples, including demo here  (https://material.angularjs.org/HEAD/#/demo/material.components.fabSpeedDial) work correctly with direction set to 'up' or 'down'  in Safari. For 'down' direction', only one button is visible (looks like overlapping others). For up - no button is visible when opened. No errors in console. Checked with Safari Version 8.0.6 (10600.6.3)

**Comment by Sayene** [comment]
The same problem in Safari on iOS (8.3) and on Android in native browser (5.0)

**Comment by topherfangio** [comment]
Thanks @Sayene, I will take a look and see if we can fix this!

**Comment by daftfox** [comment]
Im rather new at this (reporting issues), but I don't think this has been fixed yet.
I'm running version 0.10.0 of the angular-material library.
AngularJS: 1.4.3
Browser: safari 8.0S
OS: OSX 10.10

This particular problem is fixed by changing the 'height' attribute of .md-fab-actions from '100%' to 'auto'.

**Comment by topherfangio** [comment]
@daftfox This was fixed in 919ca98 which hasn't been released yet. If you use the latest version of master, or any of the `0.10.1-rc`s, you should see the fix.

I actually did `height: initial` which made it work, but have recently switched to `height: auto` in later code to fix some other issues, so these should be pushed soon too.

Can you try against the latest master version and see if it's fixed for you?

**Comment by GillesDebunne** [comment]
The FAB Speed Dial demo still does not work on Safari for me. No animation on hover.
Strangely, the 'More options' demo below works.

material.angularjs.org, HEAD = v0.11.0
angular v1.4.6
safari v8.0.8 on Yosemite 10.10.5

**Comment by topherfangio** [comment]
@GillesDebunne The top demo no longer automatically opens on hover (nor does the speed dial). This should have been noted as a breaking change in the Changelog, but I must have missed it, so I apologize. The bottom demo uses `ng-mouseenter` and `ng-mouseleave` to duplicate this functionality.

That said, I do see an issue with the close animation not firing in Safari. I will open a separate issue regarding this.

**Comment by GillesDebunne** [comment]
Indeed, my bad, I thought I also tried with a click.

I do not see any problem with the close animation BTW.

**Comment by topherfangio** [comment]
@GillesDebunne Thanks for the update! If you see anything else, definitely open a new issue :-)
