### ISSUE TITLE
Md-select with md-on-open default value

### ISSUE THREAD

**Issue by gpopovic** [angular/material#3489]
When using md-on-open (async select), there is no way to set default value which can be useful.

**Comment by rschmukler** [comment]
@gpopovic Could you not do something like:

```html
<md-select ng-model="myModel" md-on-open="loadOptions()">
  <md-option ng-repeat="opt in options" value="{{ opt.value }}">{{ opt.text }}</md-option>
</md-select>
```

```js
$scope.loadOptions = function() {
  return somethingAsync().then(function(opts) {
    $scope.myModel = opts[0].value; // Select default here
    return opts;
  });
}
```

**Comment by rschmukler** [comment]
Presuming this is resolved.

**Comment by ericman93** [comment]
+1

**Comment by Elecweb** [comment]
@rschmukler it doesn't resolve. where does scope's `options `come from? The demo in angular material website show how to implement async select by setting a scope variable to returned data from server. 
I'm wonder what the right way to implement async select?

**Comment by finchen** [comment]
try that: https://jsfiddle.net/rschmukler/0ju750xo/
I think the select should show the 'someVal' label, not the placeholder

**Comment by dklug-sisdam** [comment]
Hi, maybe someone can help me, I'm using md-select with md-on-open and I can't set selected value before select is clicked.
