### ISSUE TITLE
md-menu: md-backdrop does not get removed

### ISSUE THREAD

**Issue by stefan-schweiger** [angular/material#3741]
I have a hard time reproducing this but sometimes (like every 5th time) when using the `md-menu` the `md-backdrop` does not get removed when clicking on a menu option, and the whole site becomes *unclickable*.

This is what the end of my html page looks like when it stops working.

```HTML
<div class="md-scroll-mask" style="z-index: 50">
    <div class="md-scroll-mask-bar"></div>
</div>
<md-backdrop class="md-menu-backdrop md-click-catcher md-default-theme">
</md-backdrop>
<div class="md-open-menu-container md-whiteframe-z2 md-default-theme md-active md-clickable"
     style="top: 58px; left: 171.515625px; -webkit-transform-origin: left top 0px;">
    <md-menu-content class="md-default-theme">
        <md-menu-item>
            <button class="md-button md-default-theme"
                    ng-transclude=""
                    ng-click="vm.onSplit('vertical')"
                    ng-disabled="vm.item.sizeX <= 1"
                    aria-label="split vertical"
                    tabindex="0"
                    aria-disabled="false">

                <md-icon class="mdi mdi-split ng-scope ng-isolate-scope md-default-theme"
                         aria-hidden="true">
                </md-icon>
                <span class="ng-binding ng-scope">Split vertical</span>
            </button>
        </md-menu-item>
        [...]
    </md-menu-content>
</div>
```

**EDIT:** At first I suspected md-scroll-mask caused this, but it apparently didn't

**Comment by epelc** [comment]
I think this is the reason for my issue #3714

**Comment by stefan-schweiger** [comment]
You are probably right!

I don't open a dialog in my `ng-click` but add a item to an array which I use for `ng-repeat` so there is also some DOM manipulation going on, which I assume for some reason breaks the removal of the other DOM element.

**Comment by stefan-schweiger** [comment]
@rschmukler seems like [this](https://github.com/angular/material/issues/3714#issuecomment-121690202) fixed my issue as well, I'm closing it.

**Comment by justindujardin** [comment]
This issue is still happening intermittently in 0.10.1.  

I dug into it a bit while the bug was happening and noticed what *could* be a bug, but I'm not familiar enough with the code to say for sure.  

What I observed is that the [backdrop click handler](https://github.com/angular/material/blob/master/src/components/menu/_menu.js#L226-L236) appears to set the isOpen flag before calling the interim element hide method, which could (potentially?) reject.  When this bug is manifest, the backdrop click handler is still registered and fires, which comes in to closeMenu and immediately returns because it thinks the menu is closed.  

```javascript
  function closeMenu(skipFocus) {
    if ( !ctrl.isOpen ) return;

    ctrl.isOpen = false;
    triggerElement && triggerElement.setAttribute('aria-expanded', 'false');
    $mdMenu.hide(); // <--- Should catch and set isOpen to true?

    if (!skipFocus) {
      $element.children()[0].focus();
    }
  }
```

If the hide() method were to reject, this could cause the menu to be in a bad state.

I also notice that in the [hide() method](https://github.com/angular/material/blob/master/src/core/services/interimElement/interimElement.js#L296-L307), the catch appears to swallow any errors and never resolve.  

```javascript
      function hide(reason) {
        var interim = stack.shift();
        if ( !interim ) return $q.when(reason);

        interim
          .remove(reason || SHOW_CLOSED, false)
          .catch(function( reason ) {
            // $log.error("InterimElement.hide() error: " + reason ); <--- Errors eaten?
          });

        return interim.deferred.promise;
      }
```
Perhaps these errors never occur?

Thoughts?

**Comment by charlieysc** [comment]
same issue as @justindujardin but mine happens each time mdMenu is clicked. (refreshing the page was the only way to get rid of <md-backdrop>). This happen in 0.10.1.
Downgrading to 0.10.0 was how i got rid of this issue.

**Comment by stefan-schweiger** [comment]
you should probably open a new issue, because I guess the developers don't look much into already closed issues.

**Comment by donedgardo** [comment]
I can confirm @charlieysc post and add that clicking outside menu also doesn't remove md-backdrop unless refreshed.

**Comment by samio80** [comment]
Yes same situation after using md-menu-bar each item generates more and more md-backdrop divs

**Comment by ThomasBurleson** [comment]
@samio80, @donedgardo  - I am not able to reproduce this on https://material.angularjs.org/HEAD/#/demo/material.components.menuBar. Are you using the lastest code from master? Which version of angularJS are you using?

**Comment by donedgardo** [comment]
I am using angular@1.4.4 with: [angular-meteor](https://github.com/Urigo/angular-meteor).

**Comment by samio80** [comment]
![screen shot 2015-09-16 at 02 28 28](https://cloud.githubusercontent.com/assets/4519631/9893653/0dd321e0-5c1b-11e5-9518-f30d07d8fd0c.png)

**Comment by samio80** [comment]
These are the bower dependencies that I'm using to reproduce the error:
`
  "dependencies": {
    "angular": "1.4.x",
    "angular-animate": "~1.4.x",
    "angular-aria": "~1.4.5",
    "angular-cookies": "~1.4.x",
    "angular-i18n": "~1.4.x",
    "angular-material": "*",
    "angular-messages": "~1.4.5",
    "angular-mocks": "~1.4.x",
    "angular-password": "~1.0.1",
    "angular-resource": "~1.4.x",
    "angular-route": "~1.4.x",
    "angular-sanitize": "~1.4.5",
    "angular-touch": "~1.4.x",
    "font-awesome": "~4.4.0",
    "jquery": "~2.1.4",
    "lodash": " ^3.9.3",
    "material-design-icons": "~2.0.0",
    "modernizr": "2.6.2",
    "ng-file-upload": "7.0.12",
    "ngAutocomplete": "1.0.0",
    "google-closure-library": "*"
  },
`

**Comment by samio80** [comment]
I just also tried switching to the master (bower install angular-material#master) and the problem persists.

**Comment by samio80** [comment]
And also with this deps also can be reproduced   "dependencies": 
`{
    "angular": "1.4.4",
    "angular-animate": "1.4.4",
    "angular-aria": "1.4.4",
    "angular-cookies": "1.4.4",
    "angular-i18n": "1.4.4",
    "angular-material": "master",
    "angular-messages": "1.4.4",
    "angular-mocks": "1.4.4",
    "angular-password": "1.0.1",
    "angular-resource": "1.4.4",
    "angular-route": "1.4.4",
    "angular-sanitize": "1.4.4",
    "angular-touch": "1.4.4",
    "font-awesome": "4.4.0",
    "jquery": "2.1.4",
    "lodash": " ^3.9.3",
    "material-design-icons": "2.0.0",
    "modernizr": "2.6.2",
    "ng-file-upload": "7.0.12",
    "ngAutocomplete": "1.0.0",
    "google-closure-library": "*"
  },`

**Comment by samio80** [comment]
I don't know if it's also related with this issue, but I was just checking the performance of the toolbar-menu in my mobile using chrome latest version and I realise that the menus stay open after being clicked in.

Shall I open another issue regarding this faulty behaviour?

**Comment by samio80** [comment]
I tried with the master branch and the backdrops are still is not removed.

**Comment by ThomasBurleson** [comment]
Please open a new issue WITH a codePen demo.

**Comment by samio80** [comment]
you mean for the backdrops not removed or for the new faulty behaviour?

**Comment by samio80** [comment]
I cloned this https://material.angularjs.org/HEAD/#/demo/material.components.menuBar. and add
`
 <md-menu md-position-mode="target-right bottom">
            <button class="md-button md-default-theme ng-click-active" ng-transclude="" ng-click="$mdOpenMenu()" type="button" aria-haspopup="true" tabindex="0" aria-expanded="false">
              I will break it!
            </button>
            <div class="md-open-menu-container md-whiteframe-z2" style="display: none;">
              <md-menu-content class="md-menu-bar-menu md-dense" width="5" />
            </div>
          </md-menu>
`
As you can see this menu has not sub-items, so just hovering on this one and then hovering to the others items will break it.
I saved this one for you to see:

http://codepen.io/samio80/pen/rOeeYN

**Comment by ThomasBurleson** [comment]
The above is exactly the info that helps us quickly improve ngMaterial.
Thank you.

**Comment by samio80** [comment]
You guys are doing a really good job! I'm glad I can help ;)

**Comment by ThomasBurleson** [comment]
@See http://codepen.io/ThomasBurleson/pen/bVpQxG?editors=101

**Comment by samio80** [comment]
![screen shot 2015-09-24 at 20 43 22](https://cloud.githubusercontent.com/assets/4519631/10083058/fcd59b14-62fc-11e5-9463-fd2bbfb5d18a.png)

Now I realise that it creates submenus floating outside when the item is empty. Please see image

**Comment by ThomasBurleson** [comment]
@rschmukler - can you investigate this ?

**Comment by gaballard** [comment]
I've been running across this bug, and in my case I narrowed it down to an <md-divider> placed within <md-menu-content>. If the <md-menu-content> block begins and ends with an <md-menu-item>, you can place an <md-divider> between them without any issues. But if <md-divider> is the first or last element in <md-menu-content>, it'll throw the following console error and prevent any further interaction with the page:

```
TypeError: Cannot read property 'focus' of null
    at activateInteraction (angular-material.js:9211)
    at angular-material.js:9090
    at processQueue (angular.js:14454)
    at angular.js:14470
    at Scope.$eval (angular.js:15719)
    at Scope.$digest (angular.js:15530)
    at angular.js:15758
    at completeOutstandingRequest (angular.js:5370)
    at angular.js:5642
```

I hope this helps!

**Comment by rschmukler** [comment]
Per [this demo](http://codepen.io/rschmukler/pen/PPvzVj) this is now resolved in master. Thanks!

**Comment by WebTechnolog** [comment]
@rschmukler the problem is still there when opening menu on mouseenter
https://codepen.io/webtechnolog/pen/rNawZXp
Hover the button fastly up and down (or left-right) several times. At some point md-backdrop doesn't go away. It seems to work like this because of some delay.

**Comment by Splaktar** [comment]
@WebTechnolog please look at https://github.com/angular/material/issues/11481 to see if it is related. If so, please post your reproduction CodePen link there. If not, please open a new issue with some additional details.
