### ISSUE TITLE
Chips / mdChips (with autocomplete): Keyboard selection broken

### ISSUE THREAD

**Issue by r0b-** [angular/material#4140]
With v0.10.1 selecting an option by keyboard creates an empty chip.
(see Demo with Vegetable Options)

**Comment by PseudoCorps** [comment]
Same problem, I cried a little when I noticed this :'(

**Comment by r0b-** [comment]
#3833

**Comment by r0b-** [comment]
Same as #3833

**Comment by topherfangio** [comment]
This should be fixed in master. Can you please test again and verify that it's working for you?

**Comment by PseudoCorps** [comment]
Does https://material.angularjs.org/latest/#/demo/material.components.chips  run from master? It looks like its still broken there.

**Comment by PseudoCorps** [comment]
Almost there

<img width="259" alt="screen shot 2015-09-03 at 7 32 19 pm" src="https://cloud.githubusercontent.com/assets/2850172/9673429/25e8e7e0-5272-11e5-94d7-afaee6761b2b.png">
<img width="234" alt="screen shot 2015-09-03 at 7 32 35 pm" src="https://cloud.githubusercontent.com/assets/2850172/9673427/25e1fa66-5272-11e5-86d2-ebbdc381c3ce.png">
<img width="240" alt="screen shot 2015-09-03 at 7 32 43 pm" src="https://cloud.githubusercontent.com/assets/2850172/9673428/25e43024-5272-11e5-9f8a-6d804868713a.png">

Looks like the style changed a lot

**Comment by topherfangio** [comment]
@PseudoCorps Can you please test against https://material.angularjs.org/HEAD/#/demo/material.components.chips? That is the actual latest master code; the "latest" tag in the URL is actually the latest official release.

**Comment by r0b-** [comment]
The master version works for me (not 0.11.0!).
Unfortunately the custom item template is not compiled anymore :-(

**Comment by topherfangio** [comment]
@r0b- I think the `item` is indeed hard-coded at the moment. I'll take a look and see if we can fix it easily. If not, we'll definitely update the docs to make mention of it.

Regarding the additional empty chip issue, I cannot reproduce. Based on the images by @PseudoCorps, it doesn't look like he is using one of the demos on the site. Can one of you provide a Codepen showing the issue so that we can track it down?

**Comment by PseudoCorps** [comment]
Tested again (md website version) and it looks like it works, but I wasn't sure if this is default behavior? 

<img width="532" alt="screen shot 2015-09-14 at 11 45 23 am" src="https://cloud.githubusercontent.com/assets/2850172/9854354/6b3dc7c2-5ad6-11e5-8507-119983746b01.png">

Scroll

<img width="525" alt="screen shot 2015-09-14 at 11 45 43 am" src="https://cloud.githubusercontent.com/assets/2850172/9854358/6f20036e-5ad6-11e5-8760-ed4f831288fb.png">

**Comment by topherfangio** [comment]
@PseudoCorps Wasn't sure if what is the default behavior?

**Comment by PseudoCorps** [comment]
The option box being blank / moving when you scroll

**Comment by r0b-** [comment]
The blank chip is added if the attribute *md-require-match* is false / missing.
I don't see any documentation about it so this seems to be mandatory?

http://codepen.io/anon/pen/LpGmZK?editors=101

**Comment by topherfangio** [comment]
@PseudoCorps I just opened a new issue for the dropdown being blank: #4665

@r0b- I have also created a new issue for the hard coding of `item`: #4667.

@r0b- `md-require-match` is not mandatory, but if you don't use it, you must use the `md-on-append` attribute which is mandatory, but not very well documented. I have opened a new issue about the docs: #4666.

As it says, there are a few open PRs that will help make all of this functionality work better. Particularly, you *should* be able to return null from `md-on-append` to not add a chip, but this isn't currently available, so this is why you are getting the blank chip.

I'm going to go ahead and close this issue in favor of the other three. If you have more comments, please post them on one of these new issues or submit a new one (if it isn't covered by those).

Thanks!
