### ISSUE TITLE
md-fab-speed-dial: dynamic md-fab-actions

### ISSUE THREAD

**Issue by ptrenery** [angular/material#4277]
Hiding or removing one of the actions dynamically causes animation issues when in md-fling mode. md-scale seems fine.

Use the FAB Speed Dial demo code from the material site. Add ng-if="false" or ng-show="false" to the first 'twitter' button then expand and contract the fab buttons.

**Comment by topherfangio** [comment]
Confirmed. Thanks for finding. We'll try to get this fixed in 0.12.

**Comment by Ulrikop** [comment]
Why is this set to deprecated silently?
With version 1.07 it still have problems. When a item is added dynamically to the md-fab-actions, then it looks wrong until the menu is opend the first time.

looks wrong means (at a speed dial which opens to the left):

- if a action is added, the new state is shown at the left of the trigger, although the dialoge is closed
- if a action is removed, the old states are shown above each other right of the trigger, although the dialoge is closed


That is why I am disappointed that it now looks like if nothing would be changed

**Comment by ThomasBurleson** [comment]
This issue is closed as part of our deprecation effort.
    For details, see our post [Spring Cleaning 2016](https://groups.google.com/forum/#!topic/ngMaterial/3Ip9nd68bfk).
