### ISSUE TITLE
ng-href vs ng-click on md-menu-item

### ISSUE THREAD

**Issue by VikramTiwari** [angular/material#4342]
Why is it specific to use `ng-click`? I tried using `ng-href` and it messed up the view. And its very specific to `md-button` inside `md-menu-item`.

```
<md-menu-content>
   <md-menu-item><md-button ng-click="doSomething()">Do Something</md-button></md-menu-item>
 </md-menu-content>

```

**Comment by gligoran** [comment]
I've got the same problem with ```.md-secondary``` on ```md-list-item```. It works fine when used with ```ngClick``` but fails when ```href``` is used. In my case this is the problem because I'd like for users to be able to use the middle-click (or right-click and selecting *Open link in new tab*) to open that link in a background tab.

**Comment by rschmukler** [comment]
@VikramTiwari this should be fixed on master. If not please open a new issue re-reporting.

**Comment by idamai** [comment]
Hi, I am on 1.0.5 and I am still having this issue.

Basically I am doing
```
          <md-menu-item>
            <md-button aria-label="Google" ng-href="https://www.google.com" target="_blank">
              Google
            </md-button>
          </md-menu-item
```
and it messes up the as well.
