### ISSUE TITLE
Chips mdRequireMatch issue with Angular 1.4

### ISSUE THREAD

**Issue by langdonx** [angular/material#4436]
These two fiddles are identical, except for Angular version:

Angular 1.3.15 http://jsfiddle.net/langdonx/t2069pqz/
Angular 1.4.5 http://jsfiddle.net/langdonx/bpxa44a5/

Click find a group, type t, press enter.

The newer version doesn't honor mdRequireMatch.  After some investigation, it appears that `this.$scope.requireMatch` isn't available inside of `MdChipsCtrl.prototype.inputKeydown` (angular-material.js line 15297) when using Angular 1.4.5, instead it exists as `this.$scope.$mdChipsCtrl.requireMatch`.  I'm not familiar enough with 1.3->1.4 changes to know why this is.

**Comment by ngraef** [comment]
@langdonx Can you test with the latest build on master? `mdRequireMatch` was fixed in 86db4db9fd6e61314c1ce08cbffdffd52eae787f.

**Comment by langdonx** [comment]
Ah true, it's good on master.

**Comment by arcreative** [comment]
This still doesn't respect `md-require-match="true"` in my use case.  In my case, the chips are objects, and it just creates a bogus object that looks like a blank chip.

You can probably see this with the following data structure:

```
$scope.model = [
  {id: 1, name: 'one'},
  {id: 2, name: 'two'},
  {id: 3, name: 'three'},
  {id: 4, name: 'four'}
];
```
              '<md-chips ng-model="model"' +
                      'md-autocomplete-snap' +
                      'md-require-match="true">' +
              '<md-chip-template>{{$chip.name}}</md-chip-template>' +
              '<md-autocomplete ' +
                               //'md-selected-item="selectedItem"' +
                               'md-search-text="searchText"' +
                               'md-items="item in search(searchText)"' +
                               'md-item-text="item.name"' +
                               'md-autoselect' +
                               'placeholder="Enter skills">' +
                '<span md-highlight-text="searchText">{{item.name}}</span>' +
              '</md-autocomplete>' +
            '</md-chips>' +
```
