### ISSUE TITLE
ng-click on md-buttons within md-fab-toolbar do not work on IE

### ISSUE THREAD

**Issue by Mctalian** [angular/material#4691]
[Demo](http://codepen.io/anon/pen/MaypEV): Open the fab-toolbar, click on the right-most button (the comment button). On Chrome, the md-fab-toolbar will toggle which side of the screen it is on. On IE, nothing happens. I initially tested this with a console print, but this is a bit more visually obvious.

Angular 1.4.4, Material 0.11.0

Have not tested other versions at this time.

**Comment by topherfangio** [comment]
I'm not at my IE machine right now, but I can test this next week when I get back home and see if I can find the problem.

**Comment by Mctalian** [comment]
Has this been looked into? Do I need to provide any more demos?

**Comment by topherfangio** [comment]
Sorry; I lost track of this one when I got back home. I am headed to the office this afternoon and will look into it.

**Comment by topherfangio** [comment]
Confirmed; appears to only affect IE (tested Edge; assume 11 as well).

**Comment by darek** [comment]
Well i was trying to add md-buttons to fab-toolbar but it seems i can't get ng-click working. Buttons appear, but after clicking on them toolbar is sliding out.
Checked on safari and chrome. (newest)

**Comment by eparis** [comment]
Chrome: 48
Material: 1.0.0-rc1
[example app](http://plnkr.co/edit/EbXDK8c9c0eHgNmSz2fq?p=preview)

**Comment by eparis** [comment]
Although it is working in 1.0.0-rc2.  Wish I had those 2 hours back.  Thank you whoever fixed it!

**Comment by topherfangio** [comment]
@eparis Quite a few things have changed recently, is this also fixed for you on HEAD?

**Comment by eparis** [comment]
https://cdn.gitcdn.xyz/cdn/angular/bower-material/v1.0.0-rc2-master-ee98b70/angular-material.js seems to be working.

Note: I'm only using chrome and FF, not IE. (and both of those were broken in -rc1)

**Comment by topherfangio** [comment]
@darek That is by design. Once you have clicked a button, the fab toolbar is designed to close. We are talking about adding a `md-locked-open` attribute or something similar so that you can have better control over this, as well as other, components. Is that something you would be interested in?

**Comment by NiXXeD** [comment]
An ```md-locked-open``` feature would be useful, for sure!

**Comment by topherfangio** [comment]
@NiXXeD We have a separate issue to track and discuss `md-locked-open` (#4937).

I'm going to go ahead and close this issue since the original problem has been solved. Please post any new comments in the other thread or post a new issue.

Thanks!

**Comment by janvandenberg** [comment]
I'm still having this issue with on 1.0.2 in IE11 on Windows 10. Buttons ng-click handlers are not working

**Comment by topherfangio** [comment]
@janvandenberg The following Codepen seems to work if you click the Comment icon: http://codepen.io/topherfangio/pen/yexrxy?editors=1010

If you're still having trouble, can you please open a new issue with a Codepen that shows the trouble you're having?

**Comment by janvandenberg** [comment]
@topherfangio It works fine until you want to click on a button inside the toolbar. The $scope.check function for example?; doesn't fire when you click on it. I've change the component to a FAB SpeedDial because I could not make the FAB Toolbar work in IE11 (Windows 7)

**Comment by eparis** [comment]
That code pen (mostly) works for me on Linux + Chrome 50. Clicking on the 'comment' button inside the toolbar causes it to close and the toolbar to switch from left to right (or vice versa)

(there is some bug in here in that after clicking the comment button the open/close radio button does work the first time I click open, but does work the second time...   But that isn't what this issue was about...)

**Comment by janvandenberg** [comment]
I've tested it on Chrome, Safari and Edge. Works fine. Except not IE11 on Windows 7.

**Comment by WDShannon** [comment]
Same issue for me.  this will not work on IE11 on Windows 7. The codepen linked by @topherfangio does not work for me in IE but it will in chrome.
