### ISSUE TITLE
datepicker repositions based on body size, not visible viewport (w/ scrolling)

### ISSUE THREAD

**Issue by maddy2308** [angular/material#4781]
<img width="1440" alt="screen shot 2015-09-22 at 1 15 30 pm" src="https://cloud.githubusercontent.com/assets/4732478/10030892/f6b5ecd6-612e-11e5-8b0f-cede3b9bbde5.png">
Whenever I use the md-datepicker and if it is near the page margins it doesn't open properly. By not opening properly I mean it is not scrollable and it should by itself know where it needs to show the popup based on its space requirement. Just like the image showing it should have open on top and not keep opening in space where the user has no option to select the date

**Comment by jelbourn** [comment]
@maddy2308 
Can you check whether this is happening with the latest fixes in place? You can use:

https://cdn.rawgit.com/angular/code.material.angularjs.org/master/HEAD/angular-material.js
https://cdn.rawgit.com/angular/code.material.angularjs.org/master/HEAD/angular-material.css

**Comment by maddy2308** [comment]
I just check it with the links that you provided above and it is still persistent. The datepicker continuously open and if it open near the end of page it just doesn't  show the date picker element properly. Please find the screenshot attached.
<img width="1440" alt="screen shot 2015-09-22 at 4 10 23 pm" src="https://cloud.githubusercontent.com/assets/4732478/10034299/4e9f2308-6144-11e5-97c5-14ffc65dbd45.png">

**Comment by jelbourn** [comment]
Thinking more about it, pretty sure I know what the problem is.

**Comment by epelc** [comment]
@jelbourn Also if it's near the edge(left/right) it get's clipped

**Comment by CLGitDev** [comment]
@jelbourn Tried the latest master, the fix works for me too. Thanks for fixing the issue.
There's one small catch on the styling though - the calendar isn't truly center aligned for small screen. Please see below screenshot for reference. Any chance this can be fixed along?
![image](https://cloud.githubusercontent.com/assets/14813922/10063283/85e6a2a4-629e-11e5-9201-4801a8374e0b.png)

**Comment by jelbourn** [comment]
@CLGitDev how did you produce that Chrome problem?

**Comment by CLGitDev** [comment]
@jelbourn  Thanks for reverting. I tried again with the latest stable channel release of Chrome, the md-datepicker is now responsive. Looks like it's an issue specific to an older browser version.

I'm still seeing a margin on the right when the date picker is opened though.

**Comment by pattyjogal** [comment]
I was seeing this, now I get a bizzare spacing between all of the elements:
![image](https://cloud.githubusercontent.com/assets/13685040/10115693/f408901e-63d7-11e5-9dcd-2cf3b50cfa4e.png)

**Comment by jelbourn** [comment]
@pattyjogal It looks like your app might have some CSS that's affecting the calendar. Without a demo or some code it's impossible to tell.

Closing this now  since the main problem (calendar being off-screen) should be resolved.

**Comment by wasntme** [comment]
similar issue still exists in Firefox when having multiple datepickers

<img width="440" alt="51221308-799d-11e5-888d-33e57af61505" src="https://cloud.githubusercontent.com/assets/5786831/10694236/51221308-799d-11e5-888d-33e57af61505.png">

jsfiddle: http://jsfiddle.net/ps25aotj/

clicking the first pickers: everything ok
scrolling down -> clicking on one of the pickers: above behavior appears

**Comment by mkowalchuk** [comment]
The issue still seems to happen if the date picker is inside of a dialog. I tested with 1.0rc1, and this was the result:

![screenshot from 2015-10-27 14 23 29](https://cloud.githubusercontent.com/assets/1266924/10773016/56ace606-7cb6-11e5-88cc-a959d4a4ccc2.png)

http://codepen.io/anon/pen/bVMwmy/

**Comment by shrisowdhaman** [comment]
We can Fix this issue by using MomentDateAdapter
1.  "@angular/material-moment-adapter": "6.3.2", in package.json
2. 

export const dateFormat = 'YYYY-MM-DD';

export const MOMENT_DATE_FORMATS: MatDateFormats = {
  parse: {
    dateInput: dateFormat
  },
  display: {
    dateInput: dateFormat,
    monthYearLabel: 'MMMM Y',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM Y'
  }
};

3. 
@Component({ 
  providers: [
    {provide: DateAdapter, useClass: MomentDateAdapter, deps: [MAT_DATE_LOCALE]},
    {provide: MAT_DATE_FORMATS, useValue: MOMENT_DATE_FORMATS },
  ]
})

**Comment by Splaktar** [comment]
@shrisowdhaman Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.
