### ISSUE TITLE
layout-gt-sm adds flex-wrap

### ISSUE THREAD

**Issue by calebegg** [angular/material#4916]
For some reason, `layout="row"` works fine but `layout-gt-sm="row"` adds `flex-wrap: wrap;`. There's no way to "un-wrap" besides resorting to overriding the CSS (since there's no layout-nowrap, for example).

Demo:

https://codepen.io/calebegg/pen/BopjNG

The two containers of buttons should look the same, but the top one wraps and the bottom one doesn't.

**Comment by ThomasBurleson** [comment]
Fixed in master.

**Comment by calebegg** [comment]
Hmm. Still reproducing in the codepen, which I think is using master. (Isn't "HEAD" the same as master?)

**Comment by ThomasBurleson** [comment]
@calebegg - today we add more stabilization changes to Layouts (in HEAD/master). 
Here is your demo working properly:  http://codepen.io/ThomasBurleson/pen/qOrWKL

> Note: Developers must now *always* define the ngMaterial module dependency:
```js
angular.module('MyApp', ['ngMaterial']);
```
