### ISSUE TITLE
md-tabs: the label/body syntax does not work when inside another md-tabs

### ISSUE THREAD

**Issue by amritk** [angular/material#4989]
I found an issue using md-tabs within md-tabs using a specific syntax. When I use this syntax it works fine:
```
<!-- Finances tab -->
<md-tab label="Finance" md-on-select="$root.updateTabUrl('finance')" ng-if="true || gamesShow.resource.can_manage">
    <md-tabs md-no-bar md-stretch-tabs="always" class="inner-tabs">
        <md-tab label="Subtab-1">content</md-tab>
        <md-tab label="Subtab-2">more content</md-tab>
    </md-tabs>
</md-tab>
```
![screen shot 2015-10-02 at 1 47 19 pm](https://cloud.githubusercontent.com/assets/2039539/10257515/cb886346-690c-11e5-9ec2-a100954e038a.png)

But when I use the other syntax, so I can include icons in my inner tabs, it seems to add the inner tab to the parent tabs and replace the finance tab. This method was outlined in https://github.com/angular/material/issues/3524
```
<!-- Finances tab -->
<md-tab label="Finance" md-on-select="$root.updateTabUrl('finance')" ng-if="true || gamesShow.resource.can_manage">
    <md-tabs md-no-bar md-stretch-tabs="always" class="inner-tabs">
       <md-tab>
    <md-tab-label>
        <md-icon md-font-library="material-icons">camera_alt</md-icon>
        Subtab-1
    </md-tab-label>
    <md-tab-body>
        content
    </md-tab-body>
</md-tab>
<md-tab>
    <md-tab-label>
        <md-icon md-font-library="material-icons">location_on</md-icon>
        Subtab-2
    </md-tab-label>
    <md-tab-body>
        more content
    </md-tab-body>
</md-tab>
    </md-tabs>
</md-tab>
```
![screen shot 2015-10-02 at 1 50 57 pm](https://cloud.githubusercontent.com/assets/2039539/10257536/e7f5f3a4-690c-11e5-997b-0b14fa0b1f68.png)

**Comment by robertmesserle** [comment]
I believe this was resolved a while ago - please confirm.

**Comment by amritk** [comment]
@robertmesserle it actually still does not work

http://codepen.io/anon/pen/QjBYNP
