### ISSUE TITLE
[bug] datepicker 11.3 -> Transparant background

### ISSUE THREAD

**Issue by HBO2** [angular/material#5116]
The 11.3 release brakes the Datepicker on Chrome for MacOSX El Capitain. Result a transparant background.
![screen shot 2015-10-12 at 21 40 23](https://cloud.githubusercontent.com/assets/7763328/10436918/e635d24e-7129-11e5-92ac-fa0e4c8afad4.png)

**Comment by ThomasBurleson** [comment]
Fixed. See https://material.angularjs.org/0.11.3/demo/list

**Comment by poltorak** [comment]
@ThomasBurleson what does the list (which you've linked) with datepicker? I checked also on Safari and Firefox Developer Edition, it is not fixed unless I've missed something
