### ISSUE TITLE
md-dialog not closing anymore

### ISSUE THREAD

**Issue by kschwidder** [angular/material#5195]
With the latest HEAD the md-dialog does not close anymore.
it works in 0.11.3

md-background is hidden but dialog still stays.

**Comment by ThomasBurleson** [comment]
I am unable to reproduce this in our docs; please provide more details.

**Comment by kschwidder** [comment]
@ThomasBurleson: I have nailed it down more precisely:

1) animation is disabled.
2) dialog opacity is set to 0 and the dialog is not visible anymore (as reported once by myself)

In our app we are using menus which are triggering dialogs via directives as follows:

a)  <md-menu access-control resource="Project" operation="UPDATE,DELETE" owner="{{oid}}">
                            <div aria-label="Menu"
                                 class="md-icon-button"
                                 ng-click="$mdOpenMenu()">
                                <img class="pointer"
                                     ng-src="template/icons/view/ic_arrow_drop_down_grey600_24dp.png">
                            </div>
                            <md-menu-content>
                                <md-menu-item access-control resource="Project" operation="UPDATE">
                                    <md-button resource="Project" operation="UPDATE" project-member-workflow="member"
                                               aria-label="User prozess" ng-click="" member="user">
                                        <img src="template/icons/view/ic_create_grey600_24dp.png">
                                        {{'STANDARD_BTN_PROCESS'| translate}}
                                    </md-button>
                                </md-menu-item>
                                <md-divider access-control resource="Project" operation="DELETE"></md-divider>
                                <md-menu-item access-control resource="Project" operation="DELETE">
                                    <md-button resource="Project" operation="DELETE" delete-match-member="member" ng-click="" aria-label="undo user"
                                               member="user">
                                        <img src="template/icons/view/ic_delete_grey600_24dp.png">{{'STANDARD_BTN_DELETE'
                                        | translate}}
                                    </md-button>
                                </md-menu-item>
                            </md-menu-content>
                        </md-menu>

b) the directive triggers the dialog as follows:

                           $mdDialog.show({
                                controller: myController,
                                templateUrl: 'app/module/mod_project/views/dialog.project.customer.edit.tpl.html',
                                targetEvent: event,
                                clickOutsideToClose: false,
                                escapeToClose: false,
                                bindToController: true,
                                locals: {object: localCopy}
                            }).then(onUpdate, onAbort);

Problem is the following:

1) When disabling animation the dialog is not shown since opacity is 0
2) When animation is enabled dialog it is shown but weired behaviour...

I will try to provide a plunker but it seems that the menu interferes with the dialog in HEAD

**Comment by ThomasBurleson** [comment]
@EladBezalel - did we break something with our recent Dialog openFrom-, closeTo- features?

**Comment by EladBezalel** [comment]
@ThomasBurleson nope, but I investigated this issue before, I will take a look.

**Comment by EladBezalel** [comment]
@kschwidder works on both demos
[1](http://codepen.io/EladBezalel/pen/yYPzzG) [2](http://codepen.io/EladBezalel/pen/gaXGGx)

maybe something in your code? can you post it on CodePen please?

**Comment by topherfangio** [comment]
@EladBezalel Just ran into this myself when the button that opened the menu was no longer visible via `transform: scale(0)`.

Here is a codepen: https://codepen.io/topherfangio/pen/GpOyyg

Important note; if the button becomes immediately invisible (instead of waiting for the transition time), the dialog never appears either.

**Comment by EladBezalel** [comment]
@topherfangio awesome! Thanks :)

**Comment by kschwidder** [comment]
@topherfangio @EladBezalel : :+1: This is exactly what happens in my cases !
1) the dialog never appears sometimes which might be the button case as mentioned
2) The dialog can not be closed as described.

I have to apologize my possible documentation inconvenience from a user perspective as I am not so deeply involved into internals of the library. What I frequently do is to report errors if our productive app if not behaving correctly as before :-) 

Thx to all of your support. You are doing a great job !!!

**Comment by EladBezalel** [comment]
@kschwidder thank you, your input is very helpful!

**Comment by kschwidder** [comment]
Has this been already committed in HEAD ? I checked and the problem still exists...

**Comment by EladBezalel** [comment]
It seems so, can you please post a codepen so we could investigate it more deeply?

**Comment by kschwidder** [comment]
will try to provide one tomorrow.

**Comment by hodeyp** [comment]
don't know if this helps but I am experiencing the same issue with confirm dialogs. It only occurs if the dialog is called as the result of an action on ng-click on an md-menu item.

**Comment by websirnik** [comment]
+1. I'm triggering a dialog from a sidenav. It won't close.

**Comment by EladBezalel** [comment]
Fixed in b69551c

The problem occurs because the menu item that opened the dialog is not visible anymore when the dialog tries to close.

on 71e23e5 i added openFrom, closeTo options that made specifically for this issue,
you should specify at lease `closeTo` element and the dialog will be opened from the selected menu item and be closed to the menu open button.

**Comment by kschwidder** [comment]
Latest HEAD does not solve the issue. Is it already committed ?

**Comment by EladBezalel** [comment]
Not yet, waiting for #5302

**Comment by bluebirdtech** [comment]
+1 It seems dialogs don't close when opened from a menu. Not setting targetEvent on the dialog works around it, but of course loses the nice animation.

**Comment by EladBezalel** [comment]
@bluebirdtech the problem there is that the menu is closed when the dialog tries to go back the place he came from (menu item),
the beautiful solution is to use the `closeTo` property and set the menu trigger as the element

**Comment by jb29** [comment]
This should be documented in the changelog as a breaking change.

**Comment by Frank3K** [comment]
@jb29: I think it won't break anymore once #5303 has been pulled.

**Comment by mohitadwani** [comment]
+1 I am opening a dialog which has Jcrop API. If targetEvent is added, its opacity is 0, if it is removed, the dialog is distorted and the purpose of Jcrop is destoryed

**Comment by jordajm** [comment]
+1 - worked in 0.11.4 but not 1.0.0-rc1

**Comment by Pelu2k12** [comment]
+1

**Comment by Frank3K** [comment]
It is working on master now since commit 5c129be47078d849c08d9d7e608451dbe6cfa262. Dialogs opened from a menu animate to the middle of the page now when they are closed. 

The solution from #5303 looks nicer since that animates to the original location of the menu (if I understand correctly).

**Comment by hsiri** [comment]
my angular material version is already 1.0.1, but this issue still occurs. any thoughts on this?

**Comment by snhariharan** [comment]
Is this a issue still in 1.4.4 ?? A similar situation is happening for us!

**Comment by topherfangio** [comment]
@snhariharan Can you please open a new issue that includes a Codepen and references this one for us please?
