### ISSUE TITLE
Modals do not appear to respect theming

### ISSUE THREAD

**Issue by WillsB3** [angular/material#525]
When instantiating a modal, the modal always uses the "default" theme (e.g. the class `md-default-theme`), even though the modals DOM element is a child of `<body>` on which I have `md-theme="custom-theme-name"`.

I thought maybe we could use the $mdTheming service in our application's `.config` block to set the default theme name by calling `setDefaultTheme('custom-theme-name')` but from my initial investigation it seems as though this function is not public and so cannot be called from outside Angular Material.

What is the intended solution for applying themes to modals?

**Comment by hkjels** [comment]
I'm still seeing this issue. Has it re-appeared or what?
If I specifically add `md-theme="sometheme"` to `md-dialog`, that works.
But if I append the dialog to an element that has `md-theme` set, the styles won't apply.
I'm at `0.11.4`

**Comment by vikassaklecha** [comment]
@hkjels I'm having the same issue, can you share a snippet how you are adding to dialog?

**Comment by vikassaklecha** [comment]
snippet 

```
var alert = $mdDialog.alert({
            parent: parentEl,
            targetEvent: $event,
            scope: $scope,        // use parent scope in template
            preserveScope: true,
            theme:"my_theme",
            template:'my_html'
});
$mdDialog.show(alert);
```
theme shows up in the alert object but does not apply.

**Comment by hkjels** [comment]
I just went around the issue by passing the theme as a local. It's just two extra lines of code, so I can live with it. Still think this should be fixed, but I'm spending my time elsewhere.

**Comment by bobwah** [comment]
+1

**Comment by mjt60** [comment]
I'm also still experiencing this issue. Are we required to use md-theme in out dialogs, and pass the theme variable through locals?

**Comment by Soren234** [comment]
+1

**Comment by dpoetzsch** [comment]
I'm having the same issue, dialog is always using default theme which makes it impossible to dynamically switch themes using `md-theme`. I think this should be re-opened.

**Comment by hkjels** [comment]
@dpoetzsch even setting the parent explicitly to one with the correct theme does not solve the issue. The theme must be set within the dialog itself.

**Comment by dpoetzsch** [comment]
@hkjels http://codepen.io/dpoetzsch/pen/GjRdWp or did I misunderstand the problem?

**Comment by hkjels** [comment]
Great! I missed the part with
```
// This is the absolutely vital part, without this, changes will not cascade down through the DOM.
```
Can probably close this one now

**Comment by johannesjo** [comment]
@dpoetzsch fix doesn't work for me either unfortunately.

**Comment by dlombardi** [comment]
1.3.0 broke dialog theme inheritance from designated parent in dialog config.  Anything we can do?

**Comment by dpoetzsch** [comment]
@johannesjo As I just noticed this used to work with angular-material 1.1.1 and was broken in 1.1.2. Well, this sucks!

**Comment by brian-rowe** [comment]
I'm also having the same issue as dlombardi & dpoetzsch

**Comment by thorvx** [comment]
some news about this issue?

**Comment by codymikol** [comment]
Hey @thorvx I fixed this issue with https://github.com/angular/material/pull/11078

The merge request is approved and scheduled for 1.1.8 🐔

**Comment by codymikol** [comment]
@Splaktar You should be able to close this with https://github.com/angular/material/pull/11078 🐔
