### ISSUE TITLE
md-pagination-wrapper width is calculated incorrectly when parent container uses flex

### ISSUE THREAD

**Issue by heavysixer** [angular/material#5439]
I've encountered a problem whereby the `md-pagination-wrapper` is calculated incorrectly when the `md-content` parent has a `flex` assigned to it.

I've forked your example to show this defect:

http://codepen.io/anon/pen/RWJryx

I've also attached a screenshot showing how the wrapper forces a tab element to wrap to the next line.

![screen shot 2015-10-29 at 4 12 00 pm](https://cloud.githubusercontent.com/assets/123/10832219/261e2b64-7e58-11e5-85c5-5315a60ae90e.png)

**Comment by robertmesserle** [comment]
@heavysixer What OS/Browser are you experiencing this in?  I am not seeing it in Chrome on Mac.

**Comment by robertmesserle** [comment]
@heavysixer Ah, I think I finally saw it.  Will look into it.

**Comment by heavysixer** [comment]
@robertmesserle perfect! I am happy to spelunk this with you as well. Please let me know if there is anything I can help you with.

**Comment by ciaranj** [comment]
Ah, so *this* is my issue :) .. It only affects you if you have more than 2 tabs, in that scenario the last tab gets wrapped (and hidden) my current workaround is to have an 'extra' tab (in case that helps anyone)

**Comment by webmandman** [comment]
Thats exactly what I did: <md-tab label="" ng-disabled="true"></md-tab>.

**Comment by xiphiaz** [comment]
Okay I think I've managed to fix this issue, I can't claim to understand why the fix works - it is likely due to some 1px padding or border causing the width to be calculated incorrect. PR linked above.

**Comment by zzp8164** [comment]
It seems that adding the following css could fix this.
```
md-pagination-wrapper {
    width:auto !important;
}
```

**Comment by leventebalogh** [comment]
Cool to see this issue here, thanks @heavysixer!
@zzp8164: thanks, it is a bearable workaround until the fix is integrated to mainline.

**Comment by mcosand** [comment]
I ran into this without using flex.
Digging into it a little, it seems that tabs with subpixel widths are not handled correctly. `md-pagination-wrapper` sizes itself to the integer part of the tab width, which can be too short. Starting with width=2 may also be insufficient if there are enough tabs.

See the linked pull request for a fix.

**Comment by susu** [comment]
Thanks @mcosand! I've tested your PR and it works like a charm! Hopefully it will be merged soon.

**Comment by susu** [comment]
When is @mcosand 's PR will be merged?

**Comment by koraytaylan** [comment]
this particular one simply took my all night to get around. it was so hard even googling it correctly... I am happy that width: auto !important solves it tho. :weary:

**Comment by susu** [comment]
Any update on this? Can we help somehow to merge #6737 ? Or are there any problem with it?

**Comment by verkestk** [comment]
👍  seeing this too - specifically on Chrome 49.0.2623.110 (64-bit) on OSX.

**Comment by verkestk** [comment]
We see it consistently on OSX chrome when zooming out one stop.

**Comment by yanndupuy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  dupuyyann@gmail.com
    Domain zyapps.com has exceeded the max emails per hour (496/400 (124%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:43117 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by serveur.ex2-p10.com with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.87)
	(envelope-from <noreply@github.com>)
	id 1avsbf-001a4R-Mn
	for yann.dupuy@zyapps.com; Thu, 28 Apr 2016 22:32:16 +0200
Date: Thu, 28 Apr 2016 13:25:19 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1461875119;
	bh=sXVq8SK6HIwjqIaypWwsQXpuMawt4Rxa0mi1smOk/lM=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=dzDUd/HOcEVCxbpeZJjrQWKJvoKsgf+uxA5VJxDJCtvmvmYCwc9BdL0De42oA5sQ5
	 TOQJ8DvjvwQZOZLjExmb9eqVe03F0mgrNVMi4v6KstL26MdMzcxm1G9kLA6Fc6OvOz
	 uNE8kdOViBB01fgdMbOhlJt24P8GuNqxyiunZ2l4=

**Comment by helmuthva** [comment]
@ThomasBurleson : why was this closed? Tabs are not really usable at the moment because of this issue.

**Comment by SuneRadich** [comment]
I too have issues using 1.0.0.rc5. If tabs cant all fit on the screen, the width is calculcated wrong, and the last tab is wrapped - causing the pagination not to work.

Reintroducing the old 'hack' to just add one to the calculated width seems to fix it for me:

    function calcTabsWidth(tabs) {
        var width = 0;

        angular.forEach(tabs, function (tab) {
        //-- Uses the larger value between `getBoundingClientRect().width` and `offsetWidth`.  This
        //   prevents `offsetWidth` value from being rounded down and causing wrapping issues, but
        //   also handles scenarios where `getBoundingClientRect()` is inaccurate (ie. tabs inside
        //   of a dialog)
        width += Math.max(tab.offsetWidth, tab.getBoundingClientRect().width) + 1;
    });

**Comment by rreitmann** [comment]
We are seeing this issue as well (1.1.0-rc.5). When you go to https://metadatamanagement-dev.cfapps.io/#/en/ there should be five tabs. However on Chrome (on Ubuntu) I currently see only three tabs. When I open the developer tools the tabs appear. When you refresh the page while the developer tools are open then there are just three tabs again and you can see that the width of md-pagination-wrapper is too small causing the two missing md-tab-items to be wrapped.

**Comment by WieldSoftwareDevelopement** [comment]
I've also implemented the fix mentioned by SuneRadich above.  Work's great, thanks.

**Comment by U-like** [comment]
Hi. What happened with this? I'm still facing this issue in 1.1.0.

Is @SuneRadich 's walkaround (edit angular-material source code) the only solution for this?

Thanks.

**Comment by WieldSoftwareDevelopement** [comment]
1.1.0 resolved this issue for me.

**Comment by p-mcgowan** [comment]
This still happens in Angular 1.5.8, Material 1.1.1 when tabs have `text-transform: uppercase;` on them.

**Comment by bobsilon** [comment]
@p-mcgowan Same here, use [zzp8164](https://github.com/angular/material/issues/5439#issuecomment-157263871)'s solution.

**Comment by p-mcgowan** [comment]
@bobsilon Thanks, I've been using it but it's not the ideal situation. It also fails for dynamic translated tab names but some hacky css is ok for the time being.

**Comment by JacobPariseau** [comment]
The above solution does not work for me when there are enough tabs to require scrolling (ie, on mobile)
```
md-pagination-wrapper {
width: 999999px !important;
}
```

Seems to be working though, and appears to be a valid workaround.
