### ISSUE TITLE
md-autocomplete has a bug on demo site (in master version and 1.0.0rc2

### ISSUE THREAD

**Issue by tonyawad88** [angular/material#5448]
Hello,

md-autocomplete has a bug on the demo site.
The steps to repeat:
1. Left click on auto-complete box to open it
2. Scroll to the very bottom
3. Select "Wisconsin"
4. Click on the "X" to clear the selction
5. An Empty menu will show up with no items rendered.

<img width="786" alt="screen shot 2015-10-29 at 9 49 53 pm" src="https://cloud.githubusercontent.com/assets/3638322/10836713/280079d0-7e87-11e5-91c4-171059f9122d.png">

**Comment by aavielmd** [comment]
Hmm I tried this but it seems that the options are just hidden. Try to scroll again and the options will appear; thus this is still a bug and maybe its the md-virtual-repeat problem because it is resetting when deselecting the option.

**Comment by liveyourheart** [comment]
This happens on every md-virtual-repeat-container I've seen with over 8 items..  The repeat only renders the first 8 items (from the code, it looks like it expects 5 to fit and an extra 3), but does not reset the scroll. .

**Comment by kseamon** [comment]
Pretty strange. The virtual repeat's scroller is reporting a scrollTop of 0, but the scrollbar is all the way at the bottom. That is why the repeater is rendering items at the top, out of view. Weird. Have not found a solution yet.

**Comment by kseamon** [comment]
Also, it seems to not be a problem in FireFox.

**Comment by brenovieira** [comment]
@kseamon , indeed, I just saw this issue on Chrome.

But I tryed it now with 1.0.0.0-rc3 on Firefox and it seems there is another similar bug:

![angular material issue 5448](https://cloud.githubusercontent.com/assets/7158650/11048971/16808db4-8722-11e5-8ec8-54620fdd2e4a.png)

It just shows the first 3 items instead of 5, like in chrome:

![angular material issue 5448 1](https://cloud.githubusercontent.com/assets/7158650/11049008/4f9567dc-8722-11e5-8bb7-336ae3a4def2.png)

If I scroll (or leave the input and enter again) the error continues.
now showing at codepen:

![angular material issue 5448 2](https://cloud.githubusercontent.com/assets/7158650/11049053/b9dcedcc-8722-11e5-8a52-1793bc4effbc.png)

**Comment by brenovieira** [comment]
Nops. I just saw in Chrome too after opening code pen:

![angular material issue 5448 3](https://cloud.githubusercontent.com/assets/7158650/11049124/41a89f9e-8723-11e5-8aa4-40b196018ee5.png)

After scroll and leave and return to input the same:

![angular material issue 5448 4](https://cloud.githubusercontent.com/assets/7158650/11049129/4d97ffc0-8723-11e5-8401-781f6cf1dfb5.png)

And this issue:

![angular material issue 5448 5](https://cloud.githubusercontent.com/assets/7158650/11049175/b2f93078-8723-11e5-8465-006aebc6914a.png)

![angular material issue 5448 6](https://cloud.githubusercontent.com/assets/7158650/11049178/b612d5c0-8723-11e5-82ce-5f0f4b53abfc.png)

**Comment by kseamon** [comment]
The rc3 bug is fixed by #5579.

**Comment by hillerstorm** [comment]
No... it's not

**Comment by kseamon** [comment]
Are you still seeing the rc3 bug in rc4? I'm not. The original issue in this ticket remains unresolved (it's a doozy).

**Comment by kseamon** [comment]
The other manifestation of the "rc3 bug" should be fixed by #5908.

**Comment by tonyawad88** [comment]
Not sure if you guys are aware of this but also if you position your mouse cursor on the textbox and scroll, the suggestion list shifts down as per the screenshot below. Do you want me to open another issue for this ?
 
<img width="779" alt="screen shot 2015-11-29 at 4 09 15 pm" src="https://cloud.githubusercontent.com/assets/3638322/11460082/970c0ef4-96b3-11e5-9535-fd651e1205a1.png">

**Comment by gilad905** [comment]
The original bug (selecting an item from the bottom of the menu then clearing the selection) still reproduces on Firefox (48.0.2), as well as another, similar bug:
Opening the menu and **quickly** scrolling all the way to the bottom will render a few empty rows in the bottom of the menu.
While the list in [material.angularjs.org/latest/demo/autocomplete](https://material.angularjs.org/latest/demo/autocomplete) has ~600 items, and so scrolling needs to be pretty fast for the bug to occur, I am working with a list of ~10,000 items, where even 'standard speed' scrolling will produce the bug.

This reproduces on Firefox (but not on Chrome) and with AM v1.1.1.
