### ISSUE TITLE
md-subheader don't allows clicks.

### ISSUE THREAD

**Issue by SanderElias** [angular/material#554]
If you put an `<a>` or an `<md-button ng-click='blah()'>` inside a `mdSubheader`, the click events are not reaching the ng-click handlers.

here is a [plunk](http://plnkr.co/edit/O1kCgnR1M5fPQb3tghbH?p=preview) that show's the issue

**Comment by 3emad** [comment]
I worked around it by adding this css:

```css
.md-subheader .md-subheader-content{
    position: relative;
    z-index: 10;
}
```

it would be my suggested solution.

**Comment by ajoslin** [comment]
Thanks @3emad, I implemented something similar to your fix.

**Comment by 3emad** [comment]
@ajoslin I missed my chance to have my name on the contribution list :hamster: 
next bug, I'll race you to it :wink:

**Comment by borisirota** [comment]
@ajoslin I still have this issue. this is the [plunk](http://plnkr.co/edit/bAi8vH).  
Setting
```css
#button {
  z-index: 1;
}
```
in the css fixing it but its not a real solution.

I'm using the version in the master (0.8.0-rc1) but it happens in 0.7.1 as well (as used in the plunk)

**Comment by borisirota** [comment]
Well its not exactly the same. it's when a button is wrapped with some other element (div in the plunk)

Thanks :)
