### ISSUE TITLE
md-autocomplete, scrolling over input while menu opened, shifts dropdown list position

### ISSUE THREAD

**Issue by IvanLeonenko** [angular/material#5890]
You could easily reproduce it on demo page.

**Comment by Patrik-Lundqvist** [comment]
Caused by #5718

**Comment by ngraef** [comment]
To add some clarity, the issue is that the page is scrollable when the autocomplete input has both focus and hover. Normally, page scrolling is disabled when the input is focused (and the selection menu is open), but in this case it's enabled when the mouse is hovered over the input.

Correct me if I'm wrong, @IvanLeonenko, and I'll open this as a separate issue.

**Comment by runethh** [comment]
+1 

This issue was observed on RC6 

Tested on:
Model: Iphone 5S
Browser: Mobile Safari 8
Operating system: iOS 8.4

and

Model: Iphone 6
Browser: Safari 9 mobile
Operating System: iOS 9.1 

Note that this works on:

Model: Motorola Nexus 6
Browser: Chrome 46 
Operating system: Android Lollipop

**Comment by DevVersion** [comment]
Its fixed in #6589

**Comment by Hammild** [comment]
+1 

Still experiencing this issue on:
Model: Iphone 6
Browser: Safari 9 mobile
Operating System: iOS 9.1
