### ISSUE TITLE
contentEditable not selectable with Angular Material on Android

### ISSUE THREAD

**Issue by barryvdh** [angular/material#5937]
On Android, I can't select a contentEditable piece of text.

Without Angular material: http://codepen.io/barryvdh/pen/PPrJLr
With Angular Material: http://codepen.io/barryvdh/pen/RWzLvE

It works on desktop. Probably related to gestures/fastclick (maybe similar to https://github.com/driftyco/ionic/issues/421 ?)

FYI, I'm using https://github.com/thijsw/angular-medium-editor which used contentEditable

**Comment by MarijnMensinga** [comment]
+1

**Comment by DevVersion** [comment]
This is still a valid issue, which can cause problems on touch devices with several 3d party libraries.

**Comment by kpgarrod** [comment]
Seeing that there is a pull request, is there any chance that this could be fixed in 1.1.0? It is a serious issue for any application that uses contentEditable, ergo almost any wysiwig editor. In my experience, those editors DO NOT WORK ON MOBILE DEVICES.

**Comment by DevVersion** [comment]
Fixed with SHA https://github.com/angular/material/commit/bd1cce42ba16b733af0163011f8bb2429782b5da

**Comment by kpgarrod** [comment]
I am still experiencing this issue and have opened a new issue [here](https://github.com/angular/material/issues/9414) as requested by @DevVersion
