### ISSUE TITLE
Tooltips; Text not showing, box doubles in size with each hover

### ISSUE THREAD

**Issue by Nick-t-go** [angular/material#6291]
The text on the tool tips will not show up. Plus everytime I hover over the boxes the dark shadow area where the text should appear just doubles in size untill it fills up the entire screen. Not sure what I am doing wrong. Here is my html. I have nothing in JS altering the behavior of tooltips. 
Here is a single example of how I am using them:
```
<md-button  class="md-fab md-primary md-hue-1" aria-label="Toggle Twitter"  ng-click="toggleTweets()">
      <md-icon md-svg-icon="img/twitter.svg"></md-icon>
      <md-tooltip>
               Toggle Tweets
      </md-tooltip>
</md-button>
```
Here is my entire view:
```
<md-dialog style="height:350px; " flex-sm="100" flex-gt-sm="75" aria-label="post-detail" class="post-detail" ng-cloak>
    <form>
        <md-toolbar>
            <div layout="row" class="md-toolbar-tools">
                <h2 flex="75">{{post.content}}</h2>
                <span flex="20"
                      layout="row" layout-align="center center">{{post.votes}}</span>
                <md-button class="md-icon-button"
                           layout="row" layout-align="end center" ng-click="cancel()">
                    <md-icon md-svg-src="img/cross.svg" aria-label="Close dialog"></md-icon>
                </md-button>
            </div>
        </md-toolbar>
        <md-dialog-content>
            <div class="md-dialog-content" layout="column">
                <h4>Can you help this community member out?</h4>
            </div>
            <md-list ng-cloak  ng-hide="tweetHide" ng-repeat="reply in post.replies">
                <md-list-item class="secondary-button-padding" ng-class="{highlight: hover}" ng-mouseenter="hover = true" ng-mouseleave="hover = false">
                    <md-button class="md-fab md-primary" ng-disabled="true" aria-label="votes">{{reply.votes}} </md-button>
                    <p >{{reply.content}}</p>
                    <md-button ng-show="reply.pictures[0]" class="md-fab md-primary md-hue-1" aria-label="Picture" ng-click="showImage($event, reply.pictures[0], post._id)">
                        <md-icon md-svg-icon="img/file-picture.svg"></md-icon>
                    </md-button>
                    <!--<img flex="25" src="{{reply.pictures[0]}}" ng-src="{{reply.pictures[0]}}" layout="row" layout-align="center center" max-height="50px">-->
                    <md-button class="md-fab md-primary hue-2" aria-label="Up Vote" ng-click="vote(reply, 1)">
                        <md-icon md-svg-icon="img/arrow-up.svg"></md-icon>
                    </md-button>
                    <md-button class="md-fab hue-2" aria-label="Down Vote" ng-click="vote(reply, -1)" >
                        <md-icon md-svg-icon="img/arrow-down.svg"></md-icon>
                    </md-button>
                </md-list-item>
            </md-list>
            <md-list ng-show="tweetHide" ng-repeat="tweet in tweets">
                <a href="https://twitter.com/statuses/{{tweet.id_str}}" style="text-decoration: none;"> <md-list-item class="secondary-button-padding" ng-class="{highlight: hover}" ng-mouseenter="hover = true" ng-mouseleave="hover = false">
                    <img ng-src="{{tweet.user.profile_image_url}}" class="md-avatar" alt="{{post.user.username}}" />
                    <p style="color: black">{{tweet.text}}</p></a>
                </md-list-item>
            </md-list>
        </md-dialog-content>
        <md-dialog-actions layout="row" >
            <md-button style="background-color: lightgreen;" class="md-fab" aria-label="Reply/Comment" ng-click="showListBottomSheet($event)">
                <md-icon md-svg-icon="img/bubbles3.svg"></md-icon>
                <md-tooltip>
                    Reply/Comment
                </md-tooltip>
            </md-button>
            <md-button style="background-color: tomato;" aria-label="Report/Alert" class="md-fab">
                <md-icon md-svg-icon="img/hammer2.svg"></md-icon>
                <md-tooltip>
                    Report/Alert
                </md-tooltip>
            </md-button>
            <md-button ng-show="post.pictures[0]" class="md-fab md-primary md-hue-1" aria-label="Picture" ng-click="showImage($event, post.pictures[0], post._id)">
                <md-icon md-svg-icon="img/file-picture.svg"></md-icon>
                <md-tooltip>
                    Photos
                </md-tooltip>
            </md-button>
            <md-button  class="md-fab md-primary md-hue-1" aria-label="Toggle Twitter"  ng-click="toggleTweets()">
                <md-icon md-svg-icon="img/twitter.svg"></md-icon>
                <md-tooltip>
                    Toggle Tweets
                </md-tooltip>
            </md-button>
            <div  layout-align="end center">
                <md-button class="md-fab md-primary hue-2" aria-label="Up Vote Post" ng-click="vote(post, 1)">
                    <md-tooltip>
                        Up Vote Post
                    </md-tooltip>
                    <md-icon md-svg-icon="img/arrow-up.svg"></md-icon>
                </md-button>
                <md-button class="md-fab hue-2" aria-label="Down Vote Post" ng-click="vote(post, -1)">
                    <md-icon md-svg-icon="img/arrow-down.svg"></md-icon>
                    <md-tooltip>
                        Down Vote Post
                    </md-tooltip>
                </md-button>
            </div>
            <span flex></span>
        </md-dialog-actions>
    </form>
</md-dialog>
```

**Comment by treyhoover** [comment]
+1

**Comment by chet-manley** [comment]
No issue with toolips on a button here:
http://codepen.io/anon/pen/OMVBRN

Can you post a codepen link that demonstrates the issue occurring? 
What browser are you seeing the issue in? What version NG and MD are you using, etc?

**Comment by brianfeister** [comment]
Given, my HTML below, I'm experiencing the same thing:

```
  <div class="content-bg-accent" flex layout-padding="lg" layout="row" layout-align="space-between center"
    ng-hide="items.selected.length || filter.show">

    <h2 class="md-title">
      <md-icon md-svg-icon="manage" alt="Experiences"></md-icon>&nbsp;Experiences
    </h2>
    <div flex></div>
    <md-button class="md-icon-button" ng-click="filter.show = true" aria-label="Search">
      <md-tooltip md-direction="left">Search</md-tooltip>
      <md-icon size="lg" md-svg-icon="magnify" alt="Search"></md-icon>
    </md-button>
    <md-button class="md-icon-button" ng-click="changeView()" aria-label="View">
      <md-tooltip md-direction="left">{{ listView ? 'Show Tiles' : 'Show List'  }}</md-tooltip>
      <md-icon size="lg" md-svg-icon="{{ listView ? 'view-module' : 'view-list'  }}" alt="View"></md-icon>
    </md-button>

  </div>
```

At line `7189` of the compiled `angular-material.css` output, I have the following

```
  md-tooltip .md-content {
    position: relative;
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
    background: transparent;
    opacity: 0;
    height: 32px;
    line-height: 32px;
    padding-left: 16px;
    padding-right: 16px;
    }
```

So the `background` is set to `transparent`.  Does anyone else have an idea where or how that is supposed to later be overridden by other styles?  That would help solve this issue.

**Comment by brianfeister** [comment]
So, @chet-manley looking closely at your codepen, it appears that in your example, `angular-material` is inject a `<style>` into the document header which gives applies a `background` to `md-tooltip.md-default-theme .md-content, md-tooltip .md-content`, where my code above (and perhaps the reporter of this issue @Nick-t-go) does not have an injected style for overriding `background: transparent;` as mentioned in my comment above.

**Comment by topherfangio** [comment]
@brianfeister @Nick-t-go Rather than copy/pasting your HTML, please provide a minimal Codepen which reproduces the issue so that we can test our fixes against it to know if it is working.

**Comment by brianfeister** [comment]
@topherfangio I'd love to, the problem on my end is that my application is huge and uses many components that don't inside a Codepen, so reducing it to a simple example eliminates the complexity creating the problem.  In this demo provided above: http://codepen.io/anon/pen/OMVBRN can someone tell me how the `ngMaterial` theme is being declared?  Interestingly, I removed my theme declaration and it still happens?  Because of complexity, this is nested about 4 `ui-views` deep.  I'd love to help but reproducing my app is not the optimal way.  Consider my comments merely a confirmation of the issue if nothing else.  

*Important Note* My tooltips were fine with `ngMaterial` `v0.10.1` and are broken after updating to `v1.0.0`

**Comment by Nick-t-go** [comment]
@topherfangio project is pretty large. Not sure how to introduce all the different components I got going in just a code pen to reproduce the problem.

**Comment by brianfeister** [comment]
@topherfangio @Nick-t-go I fixed this on my end.  The `md-data-table` library https://github.com/daniel-nagy/md-data-table has a dependency on angular-material.  I had updated my angular-material version but not `md-data-table`.  As a result, the `0.10.1` material library was being included alongside the `1.0.0` package in my SystemJS dependency matrix.  So, moral of the story (and I have no idea if it relates to @Nick-t-go's original bug report) is that it's definitely a surprise that an older version of the CSS accidentally included will cause the tooltip backgrounds to break but things otherwise look fine.

**Comment by Nick-t-go** [comment]
Actually it looks like my Angular Material module is at `angular-material@0.11.4` but the css file is at 1.0 ...I have tried uninstalling, reinstalling, and updating, but I only get the `angular-material@0.11.4` module version through npm

**Comment by Nick-t-go** [comment]
@brianfeister that fixed my tooltip issue(just to clarify, I had an older install and a newer stylesheet), sorta still have a problem though. They show now, I have them in a list, and for some reason now when I load the page the last item in the list's tooltip is always visible. I even added an md-visible="false" to it yet it still displays on load.  I removed the last item and then the new last item's tooltip is visible. Not sure why this is happening. So close, so so close to getting it the way I want it.
