### ISSUE TITLE
md-grid-list: md-cols attribute was not found, or contained a non-numeric value

### ISSUE THREAD

**Issue by numerized** [angular/material#6381]
Hi Awesome Team

There's a very easy to reproduce bug that is preventing the grid list to initialize on small screens only.
The error is : md-grid-list: md-cols attribute was not found, or contained a non-numeric value

To reproduce :
- Open console.
- Resize visible screen to 320px
- open the grid list demo link : https://material.angularjs.org/latest/demo/gridList
- See the error.

Can't find any workaround for the moment. This bug does not appear on larger screens.
Is present on Chrome, Firefox, Opera.

Thanks a lot for incredible work

**Comment by numerized** [comment]
Ok found similar post
Just correct the demo : 
https://github.com/angular/material/issues/6114

Workaround

```javascript
<md-grid-list
        md-cols-xs="2" md-cols-sm="3" md-cols-md="6" md-cols-gt-md="6" 
        md-row-height-xs="3:4"
        md-row-height-sm="2:3"
        md-row-height-gt-md="1:1" 
        md-row-height="3:4"
        md-gutter-sm="4px" md-gutter-gt-xs="8px" >
    <md-grid-tile ng-repeat="tile in DomC.domainLinksInfosData | orderObjectBy: 'numChildren' : -1"
                  md-rowspan="{{DomC.span[$index].row}}"
                  md-colspan="{{DomC.span[$index].col}}"
                  md-colspan-xs="1"
                  md-rowspan-xs="2"
                  md-colspan-sm="1"
                  md-rowspan-sm="1"
                  style="background-image: url('{{tile.lastPie.urlImage}}'), linear-gradient(to bottom, #ADB2B6, #ABAEB3);-ms-background-position-x: center;-ms-background-position-y: bottom;background-position: center center;background-size: cover;">
      <div layout="row" layout-align="center center">
        <h1 style="color:white">{{tile.numChildren}} Pies</h1>
      </div>
      <md-grid-tile-footer style="background: rgba(0, 0, 0, 0.67);height:auto;padding:10px 0"><h3 style="font-size:1.2em;color:white" ng-bind-html="tile.lastPie.urlTitle"></h3></md-grid-tile-footer>
    </md-grid-tile>
  </md-grid-list>
```

**Comment by mprentic-harris** [comment]
@ThomasBurleson This was a breaking change since gridLists that worked before (1.0.0-rc4), now fail to render on xs screens using Angular Material 1.0.0. This can be reproduced a bit in the gridlist [demo](https://material.angularjs.org/latest/demo/gridList) but it's even worse for our real world cases in our app.

The gridList demos need to be updated so that more people don't run into this.

**Comment by ThomasBurleson** [comment]
Fixed with SHA https://github.com/angular/material/commit/7735a1bdaf76a8cd6d33ace3a6b9619c717ece3e

**Comment by mprentic-harris** [comment]
Should this commit also include an update to the Changelog to mention this breaking change in 1.0.0?

**Comment by mprentic-harris** [comment]
@ThomasBurleson in 1.0.1: I'm still seeing `md-grid-list: md-cols attribute was not found, or contained a non-numeric value` exception thrown when using the following sets of attributes: 
```
<md-grid-list md-cols="1" md-cols-xs="1" md-cols-sm="1" md-cols-md="2" md-cols-lg="3" md-cols-xl="4" md-row-height="7:8" md-gutter="8px">
<md-grid-list md-cols="1" md-cols-xs="1" md-cols-sm="1" md-cols-md="2" md-cols-lg="3" md-cols-gt-lg="4" md-row-height="7:8" md-gutter="8px">
<md-grid-list md-cols-xs="1" md-cols-sm="1" md-cols-md="2" md-cols-lg="3" md-cols-xl="4" md-row-height="7:8" md-gutter="8px">
```

`md-cols` as stated in the exception is very much defined and contains a numeric value (in all but the last case). You would expect `md-cols` to be the default at all sizes and then the other options like `md-cols-md` to simply override that. But nothing seems to matter atm as this exception always seems to be thrown on xs screens.

On some pages in our app, this exception has no negative effect once we add the `md-cols="1"`, but on others the gridlist doesn't render properly no matter what combination of settings we use. Either way, the exception is always thrown on `xs` screens.
