### ISSUE TITLE
md-fab-speed-dial open

### ISSUE THREAD

**Issue by emps** [angular/material#6407]
md-fab-speed-dial is always open at the first time when dom loaded, needs double click to close it

**Comment by hewaroth** [comment]
Use ```md-scale``` and ```md-open="false"```.

**Comment by emps** [comment]
thanks for the replay but not much helpin problem still there and i tried that md-open="false" befor

im on master

**Comment by hewaroth** [comment]
Show your code :-)

**Comment by Tobi3112** [comment]
I can confirm this issue with the latest 1.0.1 version

**Comment by EladBezalel** [comment]
please provide a codepen

**Comment by emps** [comment]
normal code from the example

**Comment by andrekampert** [comment]
Adding `ng-cloak` to the container fixed it for me

**Comment by eugene2005** [comment]
I can confirm this is the issue. To reproduce just remove ng-cloak in the example code for the parent container.
md-fab-speed-dial appearance should not be related to ng-cloack

**Comment by emps** [comment]
@andrekampert  thanks i will use that ng-cloak till fix comes

**Comment by appelgriebsch** [comment]
doesn't work (also the workaround with ng-cloak) if used with ui-router...:

.state('view', {
            url: '/view',
            views: {
             [...]
            'actions@app': {
                templateUrl: `${moduleConfig.path}/views/todo.actions.html`
              }
[...]

in todo.actions.html:

<div class="lock-size" layout="row" layout-align="center center" ng-cloak>
  <md-fab-speed-dial md-open="fabOpen" md-direction="up" class="md-fling">
  [...]
</div>

FAB is always opened :(. Was working with 0.11.4. Currently blocking point for me to migrate to 1.0.x. The whole sample can be found here (still with 0.11.4): https://github.com/appelgriebsch/electron-boilerplate/tree/angularjs

**Comment by emps** [comment]
try use ng-cloak with md-fab-speed-dial element and add class md-scale isntead of md-fling with mine it works also take off that md-open is not working any way

**Comment by appelgriebsch** [comment]
@emps ok, doing like so:

```html
<md-fab-speed-dial class="md-scale" md-direction="up" ng-cloak>
[...]
```

closes the speed dial, but it won't open up (even when clicked) :(

**Comment by nawrasg** [comment]
@andrekampert adding ng-cloak for the container or for the fab itself fixes the problem :+1:

**Comment by topherfangio** [comment]
Duplicate of #6111 which we are working to address.

**Comment by objecteer** [comment]
After investigation, I suspected that the problem was from jqLite. So, I added JQuery to my page and the problem was solved.

**Comment by Darksoulsong** [comment]
1.0.8 version and this is still happening. It seems that the `aria-hidden` attr from `mb-fab-actions` is toggling as expected, and the same goes to the classes (`md-is-open` is applied to the mb-fab-speed-dial element), but the action buttons are always visible.

**Comment by abinthomasonline** [comment]
I tried the ng-cloak with md-scale fix successfully...

It works perfectly even if i remove ng-cloak with md-scale.. :)

**Comment by recursionbane** [comment]
I'm still seeing this issue in 1.1.0-rc5, with ng-cloak and with either md-scale or md-fling.
I'm using the same code as the example.

**Comment by EladBezalel** [comment]
@recursionbane please file a new issue about it and we will re-investigate, thanks!

**Comment by sbaechler** [comment]
@recursionbane ng-class has to be a string. Your example works if you change it to `ng-class="'md-fling'"` or `class="md-fling"`.

**Comment by sbaechler** [comment]
I still have the issue that the component does not work when used with ui-router (and jspm). It looks like the animations are not bound correctly. 

The function `MdFabSpeedDialScaleAnimation` never gets called. 

I am using material-ui 1.1.0.
