### ISSUE TITLE
Codepen and validation in demo is not working

### ISSUE THREAD

**Issue by mimani** [angular/material#6415]
Hi,

Codepen for [autocomplete demo: FloatingLabel] (https://material.angularjs.org/latest/demo/autocomplete) is not working. Also this demo has validation, but errors are not show when we leave name field blank.

**Comment by mimani** [comment]
HI, 

I corrected the [codepen](http://codepen.io/anon/pen/xZORXL) by changing the path of source libraries, still validation are not working.

**Comment by mprentic-harris** [comment]
Should be fixed now by @topherfangio in https://github.com/angular/material/commit/43464d034ad4dd43156a0b804edb4f4956484302. Try https://material.angularjs.org/HEAD/demo/autocomplete as I can see validation working there now.

**Comment by mimani** [comment]
@mprentic-harris Validation related to required is still not working, If you leave it blank, It should show error: required.

**Comment by DevVersion** [comment]
@mimani Should be fixed in #6803
