### ISSUE TITLE
mdToast removed early

### ISSUE THREAD

**Issue by csvn** [angular/material#6633]
If a toast is created when an existing toast's remove animation is underway will remove the newly created toast early.

See example at codepen:
http://codepen.io/csvn/pen/XXgBvm?editors=101

**Comment by DevVersion** [comment]
@csvn Thanks for the great demo. I know I've fixed that a long time ago, but I've discarded those changes, because the fix can be more elegant. 

So the fix will be deployed in the future / soon. 

Additionally, I will close that issue, because we already have a previous filed issue for that. #4822

**Comment by kdeclerck** [comment]
What's the status of this issue? We're still seeing this behavior in 1.1.20.

**Comment by Splaktar** [comment]
@kdeclerck please open a new issue with a reproduction.
