### ISSUE TITLE
md-menu - Blocking All Mouse Events

### ISSUE THREAD

**Issue by RichOren** [angular/material#7209]
Hello,

I have a weird bug in the md-menu in version 1.0.4+ that I have stumbled upon. 

It seams to be Blocking all mouse events when it occurs but I do not know what is causing it to do this. All I know for sure is 1.0.3 is working and when I try to upgrade to a later version then it happens. 

I have documented this with a screen capture 

video and will try to recreate with a code pen when time permits.

[Working Menu - v1.0.3](https://www.dropbox.com/s/7wvelafffqa6e35/Google%20Chrome%20-%20Menu-104.mp4?dl=0)

[Menu w/Bug - v1.0.4+](https://www.dropbox.com/s/i5qe51rek0y2684/Google%20Chrome%20-%20Menu-104.mp4?dl=0)

_

> You'll need to download the video from DB they wont play in the Flash Player they have.

_

I am sorry I do not have a Idea how it is occurring, I will try to investigate this more and try to fix it if I can.

**Comment by cah-alexsukhodolsky** [comment]
@RichOren I wasn't able to load your 1.0.4 video but we're also running into the same issue. 

I originally opened issue [6545](https://github.com/angular/material/issues/6545) requesting a fix for an issue where the md-menu never removed the md-backdrop--and was causing the same behavior as you're experiencing. The fix was to clean up the md-backdrop during the md-menu controller's destroy operations--and was patched in v.1.0.4.

But we've since been experiencing issues with the md-scrollmask blocking input. When it happens and you right-click on the page and choose 'Inspect' what element is selected in the DOM?

**Comment by ThomasBurleson** [comment]
Fixed.

**Comment by RichOren** [comment]
Tested in /angular/bower-material@master and the problem still exists.

**Comment by RichOren** [comment]
@ThomasBurleson @cah-alexsukhodolsky - It seems if I delete a widget about the third time it hangs and does not remove the md-backdrop - and sometimes both the md-backdrop and md-scroll-mask
