### ISSUE TITLE
mg-list-item not executing primary action

### ISSUE THREAD

**Issue by char0n** [angular/material#7528]
Only affected browser is Firefox. I can reproduce the issue on Firefox 44.x and Firefox 45.0
Latest Chrome and IE11 seems to be working fine.

Basically this bug manifests it self as user not being able to click on item with primary action, which is really a big issue.

You can reproduce the issue directly on documentation page:

Affected version: 1.1.0-rc1
Url: https://material.angularjs.org/latest/demo/list
Section: Avatar with Secondary Action Icon
Actual Behavior: clicking on Janet Perkins does not trigger primary action on list-item
Expected Behavior: clicking on Janet Perkins opens md-dialog

**Comment by DevVersion** [comment]
Fixed in `HEAD` / `master` by 497190b72a552b67a39222d087c87958ab359ced

**Comment by darkmavis1980** [comment]
It's still broken today, I'm using version `1.1.0-rc1` and the primary click is not working in Firefox

**Comment by DevVersion** [comment]
As I said, it's fixed in `master` / `HEAD` - that's not v1.1.0rc1

**Comment by darkmavis1980** [comment]
Ah sorry

**Comment by DevVersion** [comment]
No worries :+1: Thank's for keeping track.
