### ISSUE TITLE
md-card height doesn't adjust properly to respect scaled-down image size in IE

### ISSUE THREAD

**Issue by sstorie** [angular/material#761]
Please forgive me if I'm misunderstanding the root cause of this, but I'm trying to create a "masonry layout" where I've got multiple columns of images that are different dimensions. I'm trying to use cards to hold each image, and in Chrome and Firefox it works exactly as I expect. The card scale to the window (using flex) and the images scale the match the size of the cards.

However, on IE 11 the height of the cards seems to stay with the actual height of the image, even if it's being scaled down to a smaller size. I've created a Codepen that demonstrates the problem:

http://codepen.io/sstorie/pen/myJWxQ

You can see in IE that the images that are orientated horizontally scale their height down to fit the width of the card, but the height of the card doesn't scale down with it. It remains that the height of the image.

Is this a bug in md-card, or do I just have to add some IE-appropriate CSS? If it's an IE thing, any guidance on what should be added to make this flow properly?

**Comment by Splaktar** [comment]
I've updated the Codepen to 0.8.3: http://codepen.io/Splaktar/pen/Kwxmxa
I will test with IE 11 when I am able to get to a Windows machine. But there are certainly some flexbox issues in IE 11 that still need to be worked out. Some may be fixable with `-ms` prefixes.

**Comment by Splaktar** [comment]
This seems to be fixed or at least doing a lot better now. See the image attached here from IE 11 with the updated codepen. It looks like the images are stretched to fit the card.

![ie11_card_image_scaling](https://cloud.githubusercontent.com/assets/3506071/6566487/97671414-c690-11e4-9e91-8c4d8db68b4a.png)

**Comment by ThomasBurleson** [comment]
Fixed.

**Comment by Frank3K** [comment]
Unfortunately I don't think this is fixed. Screenshot of the current demo-site (using `master`) in Internet Explorer 11.

![material_ie_stretch](https://cloud.githubusercontent.com/assets/8014077/9830822/4fb5e902-593d-11e5-82ef-4f46d2b0d2ce.png)

**Comment by Frank3K** [comment]
@ThomasBurleson: This issue still exists in Internet Explorer 11. Can you re-open this issue or should I create a new one?

**Comment by j-slvr** [comment]
issue still exists for me (1.0.4 @ chrome 48) 
surprisingly, in ms edge it works

**Comment by j-slvr** [comment]
OK, I tested a little bit. 

It is **working** in: 
- Firefox 44
- Edge 25 
- Vivaldi

**Not working** in: 
- Chrome 48
- Opera 34

Everything on **Windows**
In Chrome for Mac it's working.

**Comment by Noppey** [comment]
+1, microsoft edge adjusts image height to scale with max width, chrome keeps height at natural height.

**Comment by ThomasBurleson** [comment]
Please see #6981
