### ISSUE TITLE
mdSwitch: within mdListItem, mdSwitch toggles on mdSlider

### ISSUE THREAD

**Issue by jsiegmund** [angular/material#7937]
I've got a md-list-item which contains both a md-slider as well as a md-switch. Whenever the user clicks/drags the md-slider, this event is also propagated to the md-switch which then toggles. Whenever other controls are present within the same list-item, md-switch should only toggle by clicks on the control itself. 

Codepen: http://codepen.io/jsiegmund/pen/repwyR

Angular version: 1.5.3
Browser: using Chrome 49.0.2623.110 on Windows 10
Possibly related: https://github.com/angular/material/issues/2594

**Comment by DevVersion** [comment]
@jsiegmund This is not how the list item should be used.

- The switch is always toggling, because it's tracked as a proxy element.<br/>
  This is a default Material Design behavior.

Proxied Elements are:
`md-switch` and `md-checkbox`.

**Comment by ThomasBurleson** [comment]
@DevVersion - if I understand the reported issue, it appears to be a valid bug. Clicking or dragging a switch should ONLY affect the enabled switch. The events should not propagate to parent containers; unless the `md-switch` is disabled.

**Comment by jsiegmund** [comment]
@ThomasBurleson it's not clicking / dragging the switch, but dragging the slider. That toggles the switch in the same list item. When you replace the list item with a div, everything behaves as expected.

**Comment by DevVersion** [comment]
@ThomasBurleson Clicking or dragging is only affecting the switch, as expected.

- See the `Clickable Items with Secondary Controls` demo [here](https://material.angularjs.org/HEAD/demo/list).

**Comment by ThomasBurleson** [comment]
@DevVersion - I strongly disagree. Switch and Slider should not trigger the other's listeners. 
See PR #7966.

**Comment by uxitten** [comment]
+1 i have this problem

**Comment by uxitten** [comment]
fixed bug with this trick

```
<md-switch ng-if="true" ng-model="data.cb1" >
          Switch
</md-switch>
```

**Comment by Splaktar** [comment]
Note that due to https://github.com/angular/material/commit/97e30d837ba3e94e37a2b051245605eadf8a0fb9#r35243082, this was only fixed in Chrome. This issue still exists for all other browsers. I'm looking at resolving this as part of fixing https://github.com/angular/material/issues/11756.
