### ISSUE TITLE
Don't want to show md-calendar-month on date picker

### ISSUE THREAD

**Issue by shruti0207** [angular/material#9260]
Is there an any option that user can only select year and month in datepicker, the date views should not shown to user. once the user select the year and month is close the calendar and it show the select date in MM/YYYY format   that also in some specific field not in complete application.

**Show only year and month view**
![year-month-view](https://cloud.githubusercontent.com/assets/20793272/17471178/e595cfd8-5d5f-11e6-81cf-00a1ef38657c.png)

**Hide date view**
![date-views](https://cloud.githubusercontent.com/assets/20793272/17471190/00871450-5d60-11e6-8155-5d161ca7ece3.png)

**regrading #9246**

I try parseDate and formatDate methods on the $mdDateLocaleProvider but it format the date when date is selected from the calendar, if date enter using keyboard in number format (08052016) it not get formatted as (08/05/2016)  and if make the change in mdDatelocalProvider than the date format change every where in application, just need to change the date format in some specific field only

**Comment by crisbeto** [comment]
It's not possible, but it seems like it could be useful.

**Comment by jagmindersingh** [comment]
+1

**Comment by shruti0207** [comment]
Date is not getting format if user enter the date using keyboard in mm/dd/yyyy format and it also not get validate. Is there any way if user enter the date through keyboard it get format and same date select on calendar.

![image](https://cloud.githubusercontent.com/assets/20793272/17921947/168effb4-69fa-11e6-9273-6295949839e6.png)

**Comment by summerisgone** [comment]
@crisbeto How'd see this option implemented? My suggestion is add ``md-select-month`` option to allow selecting months rather than dates.

**Comment by artharrison** [comment]
+1 on this.  

I need to implement this in a current project.  It would be create if we could do md-select-month == true and have the year view loaded and close when the month is selected.

**Comment by crisbeto** [comment]
Sorry, I was away last week. I'll try to get this sorted soon, although it also depends on https://github.com/angular/material/issues/9270 since it needs to be able to do different formatting.

**Comment by ryan-kimber** [comment]
Thanks for doing tackling this. I've put together [a Plunkr](https://plnkr.co/edit/nJyHfu?p=preview) and I'm running into a couple of issues when I've tried it out.

1. If I specify initial view of month and 'day' as the mode, I can't click the month to step out to change years.
2. If I specify 'year' as the initial view, I can no longer pick a day, even if the mode is day. This would be useful if you were picking a birthdate, for example.

In [the Plunkr](https://plnkr.co/edit/nJyHfu?p=preview) the first date picker should let you pick a day, and start with the current month. The second date picker should start with the month/year view, but let you pick the day when you select a month. The third date picker behaves as expected - it should allow you to pick a year/month but not a date.

I hope this is helpful and that I'm not just making some silly mistake.

**Comment by ryan-kimber** [comment]
Hold on - I may have had files from before you marked this as complete. I'll rebuild tomorrow and provide an update.

**Comment by crisbeto** [comment]
Perhaps I misunderstood the use case @ryan-kimber, but I though the idea was to be able to limit the user to only selecting a certain type of date (e.g. only the day or only the month). In order for that to work, `md-mode` has to override `md-current-view` and disable navigation between views. Here's how each of your examples should be:

1. This shouldn't use `md-mode` at all since it's just the standard calendar. If you give it `md-mode="day"`, it will limit the user to _only_ selecting a day.
2. Starting off with the year, but still selecting a date - This also doesn't need `md-mode`, it just needs `md-current-view="year"`.
3. This one is as expected.

**Comment by ryan-kimber** [comment]
Ahh. I see. It would be pretty helpful then (at least for projects like
ours) to have md-mode='default'.

We dynamically create a lot of elements, so being able to do
'md-mode={{::dateConfig.mode || 'default'}} would save us from having to do
an ng-if and having two md-datepickers in our template. Anything we can do
to keep code size and number of watches down, we try to do.

I've updated my plunkr to show two dates for each 'date-config' I'd created
and you are correct, it works as you designed.

Would you consider my request to add an option for 'md-mode="default"'?

Thanks.

**Comment by crisbeto** [comment]
Sure, I'll re-check since it was supposed to also work if the `md-mode` was empty, but it doesn't seem like it is.

**Comment by crisbeto** [comment]
You should be able to set `default` (or any other invalid value) now @ryan-kimber. Only the valid ones will prevent navigation.

**Comment by ryan-kimber** [comment]
Excellent. Thank you.

**Comment by aaroncalderon** [comment]
@ryan-kimber I was checking your Plunker, but did not load? Seems like some links to files (angular css js) at  __https://static.formhero.io/formhero/__ return a 403 error.

**Comment by ryan-kimber** [comment]
Ahh. Yes. This issue was resolved and there have been updates to support
custom date labels, so I removed the old custom-build angular-material
files.

**Comment by aaroncalderon** [comment]
@ryan-kimber mmm I am pretty much trying to acheive the same. Where you let the user selcet a year/month but no date (day) but have not figured out how.

Would you care to share how you configured the component?

**Comment by volmerf** [comment]
The Plunkr still isn't working yet. Could someone provide a snippet on how to achieve the month/year selector only without the need to select a date? md-current-view="year" will give the preferred view but clicking will still go to the day select view. Would be great to override this with a setting. Thanks!

**Comment by crisbeto** [comment]
The changes needed haven't been merged yet @volmerf

**Comment by ryan-kimber** [comment]
I've update the [Plunkr ](https://plnkr.co/edit/nJyHfu?p=preview)so that it works.

As crisbeto noted though, this isn't yet merged into Angular-Material proper. If you want to use this you'll either have to copy the angular-material .js and .css from the plunkr, or clone the angular-material repository, make a branch, manually merge the two pull requests for this issue and the custom label for date fields issue and finally run 'npm install && gulp' to build your own custom distribution.

Working in the [Plunkr at https://plnkr.co/edit/nJyHfu?p=preview](https://plnkr.co/edit/nJyHfu?p=preview)

**Comment by chetan01b** [comment]
@ryan-kimber Can we achieve only year select mode in `md-datepicker `, If yes then How can I achieve this functionality? Actually, this is needed when we select financial year or something like that.

Waiting for response.

**Comment by ryan-kimber** [comment]
If you only want year, why not use an md-select?

The reason for using a md-datepicker is to handle the multiple interactions
required to pick year/month/date and to have the number of days in each
month looked after.

If you are only selecting year, a select box should work just fine.

**Comment by aaroncalderon** [comment]
@ryan-kimber Sometimes the presentation can make the difference between well received application or not. 

So, if `md-datepicker` helps the developer deliver a better user experience, then go for it, right?

**Comment by ryan-kimber** [comment]
... but there is no view in md-datepicker that is year only.

Let me turn this around. Why do you think that using md-datepicker to
select only the year would be a better experience or presentation than an
md-select?

Would it not be more confusing to show months that cannot be selected?

If you are wanting to resolve the date value to year only, you can easily
do that in your controller.

**Comment by chetan01b** [comment]
![image](https://cloud.githubusercontent.com/assets/24645984/21447330/41332aca-c8f9-11e6-8a40-cbff94b3f729.png)

@ryan-kimber I want to create a UI same as showing in attached, Could that be possible using md-select?
If yes, Please let me know how? angular-material must have such options.
A library is incomplete till it provides complete customization to users.

**Comment by aaroncalderon** [comment]
@ryan-kimber You are right. If we do not have a year only view, then, using `md-datepicker` as @ryan-kimber suggest is a no go.

Perhaps, this could be a feature request.

**Comment by vivek147** [comment]
Could you please provide me the snippet for selecting month/year only mode ?

**Comment by AshokGurram** [comment]
@ryan-kimber 

https://static.formhero.io/formhero/js/material/v1.1.1-fh-build/angular-material.min.js


The snippet provided here is working very nice.
But the only thing is:

It is working only if we have used 

https://static.formhero.io/formhero/js/material/v1.1.1-fh-build/angular-material.min.js

this in our application.

I am not able to achieve this using
https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.1.1/angular-material.min.js

If i have changed, i need to recheck whole my application.
Can i get the way to implement this using 
https://cdnjs.cloudflare.com/ajax/libs/angular-material/1.1.1/angular-material.min.js

**Comment by shijithkm** [comment]
We cannot use latest material version if you use below custom code. 
https://static.formhero.io/formhero/js/material/v1.1.1-fh-build/angular-material.min.js

Can you please make it separate ?

**Comment by ryan-kimber** [comment]
Unfortunately, these changes did not make it into Angular Material 1.1.3, and aren't totally trivial port over (you could use the directive decorator and override the md-datepicker and it's child directives, but that's not exactly trivial).

So the options are: 

1. Live without this functionality until Angular Material 1.2 (which should have these changes)
2. Clone the Git repository for 1.1.3, then merge the pull request for these changes, build the dist to create your own custom version of 1.1.3.

**Comment by lukasborawski** [comment]
I've used pointer-events with CSS.

**Comment by andreuccia** [comment]
@lukasborawski Could you post the code of pointer-events ?

**Comment by aigdonia** [comment]
is this feature planned to be presented in next release??

**Comment by tom94zoe** [comment]
I am praying to god it is

**Comment by viniciusfont** [comment]
Nothing new yet?

**Comment by kresimirfijacko** [comment]
+1
any updates on this one?

**Comment by FRSgit** [comment]
+1

**Comment by pedrinhok** [comment]
+1

**Comment by viniciusfont** [comment]
+1

**Comment by Splaktar** [comment]
The PR is being considered for merging atm.

**Comment by muthu0101** [comment]
When we can expect this option, if you can say any proximate date it'll be great.

**Comment by ohjames** [comment]
Hm, updated to @angular/material 5.2.1, added `matMode=month` and nothing changed. Guess it still hasn't been released.

**Comment by Splaktar** [comment]
@ohjames Please submit Angular Material questions [here](https://groups.google.com/forum/#!forum/angular-material2) and issues [here](https://github.com/angular/material2/issues). This repo is for AngularJS Material.

**Comment by fsitios** [comment]
> Hm, updated to @angular/material 5.2.1, added `matMode=month` and nothing changed. Guess it still hasn't been released.

Any news about this feature? Thanks.

**Comment by Splaktar** [comment]
@fsitios yes, it's supported in AngularJS Material `v1.1.6+`. If you have questions about a similar feature in Angular Material, please ask on their [forums](https://groups.google.com/forum/#!forum/angular-material2).
